#!/usr/bin/env python
"""
gen_halo_stl.py - build every printed HALO part from halo_params.scad (PROJECT SCRATCH, 2026-10-02)

  <cadenv>/bin/python gen_halo_stl.py            # STLs + SCAD + checks
  <cadenv>/bin/python gen_halo_stl.py --set HL=201 --set HB=158    # try other tape-fit numbers

Writes  stl/<part>.stl   (watertight, mm, frame per README.md)
        scad/<part>.scad (OpenSCAD source; include <../halo_params.scad>; open and F6/F7)
        stl/_assembly_preview.stl (NOT for printing: parts + dummy tubes/strip/Airpel at alpha 0, beta 0)
Prints  part table (bbox, volume, PA12 mass, watertight) and the interference sweep.
Exit code 0 only if every part is watertight and every interference check passes.
"""
import os, sys, math
import numpy as np
import trimesh
from manifold3d import Manifold
import scadpy as sp
from scadpy import load_params, V
import halo_parts as hp

HERE = os.path.dirname(os.path.abspath(__file__))
RHO_PA12 = 1.01e-3    # g/mm3, MJF PA12 solid


class NS:
    def __init__(self, d):
        self.__dict__.update(d)


def get_params(over=None):
    P, vals = load_params(os.path.join(HERE, "halo_params.scad"), over)
    return NS(P), vals


# ----------------------------------------------------------------- placement helpers (preview / checks only)
def place_node(m, beta, alpha_b, R):
    b = math.radians(beta)
    return m.rotate([0, 0, 90]).rotate([-beta, 0, 0]).translate([0, R * math.sin(b), R * math.cos(b)]).rotate([0, -alpha_b, 0])


def place_car(m, beta, alpha_b, RSI):
    b = math.radians(beta)
    return m.rotate([0, 0, -90]).rotate([-beta, 0, 0]).translate([0, RSI * math.sin(b), RSI * math.cos(b)]).rotate([0, -alpha_b, 0])


def tube_between(a, b, r=4.0):
    a, b = np.array(a, float), np.array(b, float)
    d = b - a
    L = float(np.linalg.norm(d))
    ay = math.degrees(math.acos(d[2] / L))
    az = math.degrees(math.atan2(d[1], d[0]))
    return Manifold.cylinder(L, r, r, 24).rotate([0, ay, az]).translate(a.tolist())


def bail_tubes(v, alpha_b):
    """dummy carbon tubes (chords + legs) in H at alpha_bail"""
    R = v["R_BAIL"]
    ch = v["CH_DEG"]
    out = None
    nodes = []
    for k in range(-3, 4):
        b = math.radians(k * ch)
        nodes.append([0.0, R * math.sin(b), R * math.cos(b)])
    for i in range(6):
        a, b = np.array(nodes[i]), np.array(nodes[i + 1])
        d = (b - a) / np.linalg.norm(b - a)
        t = tube_between(a + d * v["SOCK_BOT"], b - d * v["SOCK_BOT"])
        out = t if out is None else out + t
    for s in (-1, 1):
        sh = np.array([0.0, s * v["SH_Y"], v["SH_Z"]])
        hub = np.array([0.0, s * v["Y_HUB"], 0.0])
        d = (hub - sh) / np.linalg.norm(hub - sh)
        out = out + tube_between(sh + d * v["SOCK_BOT"], hub - d * v["LEG_T0"])
    return out.rotate([0, -alpha_b, 0])


# ----------------------------------------------------------------- main
def main():
    over = {}
    args = sys.argv[1:]
    while "--set" in args:
        i = args.index("--set")
        k, val = args[i + 1].split("=")
        over[k] = float(val)
        del args[i:i + 2]
    p, v = get_params(over)
    outdir = "stl"
    if "--out" in args:
        outdir = args[args.index("--out") + 1]
    os.makedirs(os.path.join(HERE, outdir), exist_ok=True)
    os.makedirs(os.path.join(HERE, "scad"), exist_ok=True)
    parts = hp.parts(p)
    ok = True
    rows = []
    meshes = {}
    for name, (sol, frame, qty, note) in parts.items():
        tm = sp.to_trimesh(sol)
        wt = bool(tm.is_watertight) and bool(tm.is_volume)
        nb = len(sol.m.decompose())
        ok &= wt and nb == 1
        tm.export(os.path.join(HERE, outdir, name + ".stl"))
        if outdir == "stl":
            with open(os.path.join(HERE, "scad", name + ".scad"), "w") as f:
                f.write("// %s  (qty %d; frame: %s; %s)\n" % (name, qty, frame, note))
                f.write("// GENERATED by gen_halo_stl.py from halo_parts.py. Change numbers in halo_params.scad.\n")
                f.write("// Every dimension below is an expression of the names in halo_params.scad.\n")
                f.write("include <../halo_params.scad>\n\n")
                f.write(sol.s + "\n")
        bb = tm.bounds
        ext = bb[1] - bb[0]
        mass = tm.volume * RHO_PA12
        rows.append((name, qty, ext, tm.volume, mass, wt, nb, note))
        meshes[name] = sol.m
    print("\n%-22s %3s %24s %10s %8s %5s %4s" % ("part", "qty", "bbox x y z (mm)", "vol mm3", "g PA12", "wt", "bod"))
    for name, qty, ext, vol, mass, wt, nb, note in rows:
        print("%-22s %3d %8.1f %7.1f %7.1f %10.0f %8.2f %5s %4d" % (name, qty, ext[0], ext[1], ext[2], vol, mass, wt, nb))
    tot = sum(r[4] * r[1] for r in rows if not r[0].startswith(("H19", "H20")))
    print("printed head-borne mass (PA12, qty applied, tools excluded): %.1f g" % tot)
    with open(os.path.join(HERE, outdir, "_part_table.csv"), "w") as f:
        f.write("part,qty,bbox_x,bbox_y,bbox_z,volume_mm3,mass_g_PA12,watertight,bodies,print_note\n")
        for name, qty, ext, vol, mass, wt, nb, note in rows:
            f.write("%s,%d,%.1f,%.1f,%.1f,%.0f,%.2f,%s,%d,%s\n" % (name, qty, ext[0], ext[1], ext[2], vol, mass, wt, nb, note))

    # ---------------- assembly preview (not for printing)
    asm = preview(p, v, meshes)
    sp.to_trimesh(sp.S(asm, "")).export(os.path.join(HERE, outdir, "_assembly_preview.stl"))
    # ---------------- interference sweep
    print("\nINTERFERENCE / CLEARANCE CHECKS")
    chk_ok = checks(p, v, meshes)
    ok &= chk_ok
    print("\nALL OK" if ok else "\nSOMETHING FAILED (see above)")
    return 0 if ok else 1


def preview(p, v, M):
    """parts + dummy bought parts at alpha_pad 0, beta 0, float at full retract (head frame H)."""
    ab = v["DELTA"]                                      # bail angle that puts the pad at alpha 0
    hub = lambda m: m.rotate([0, -ab, 0])
    out = M["H01L_hub_plate"] + M["H01R_hub_plate"] + hub(M["H04L_foot_left"]) + hub(M["H05R_foot_right"])
    out = out + M["H13_forehead_node"] + M["H14_trigger_plate"] + M["H15L_cradle_arm"] + M["H15R_cradle_arm"]
    out = out + bail_tubes(v, ab)
    for k in (-2, -1, 1, 2):
        out = out + place_node(M["H07_chord_node"], k * v["CH_DEG"], ab, v["R_BAIL"])
    out = out + place_node(M["H08a_vertex_half"] + M["H08b_vertex_half"], 0, ab, v["R_BAIL"])
    out = out + place_node(M["H09L_shoulder_node"], 3 * v["CH_DEG"], ab, v["R_BAIL"])
    out = out + place_node(M["H09R_shoulder_node"], -3 * v["CH_DEG"], ab, v["R_BAIL"])
    car = M["H10_carriage"]
    air = Manifold.cylinder(v["RHO_BODY1"] - v["RHO_PLATE1"], v["AIR_OD"] / 2, v["AIR_OD"] / 2, 32).translate([0, 0, v["RHO_PLATE1"]])
    rod = Manifold.cylinder(v["RHO_NOSE"] - v["RHO_SPIDER_TOP"] + 5, v["AIR_ROD_D"] / 2, v["AIR_ROD_D"] / 2, 16).translate([0, 0, v["RHO_SPIDER_TOP"]])
    fl = (M["H12_spider"].translate([0, 0, v["RHO_SPIDER_TOP"]]) + air + rod).rotate([-v["DELTA"], 0, 0]).translate([0, 0, -v["R_SI"]])
    out = out + place_car(car + fl, 0, ab, v["R_SI"])
    # head ellipsoid for scale
    head = Manifold.sphere(1.0, 48).scale([v["HA"], v["HBB"], v["HCZ"]])
    return out + head


def vol(m):
    return m.volume() if hasattr(m, "volume") else m.get_volume()


def checks(p, v, M):
    ok = True

    def rep(name, val, passed, unit="mm3"):
        nonlocal ok
        ok &= passed
        print("  %-62s %10.2f %-4s %s" % (name, val, unit, "PASS" if passed else "FAIL"))

    # 1. hinge-zone: foot vs boss over alpha_bail range (rotate the foot about the hub axis)
    boss = M["H01L_hub_plate"]
    foot = M["H04L_foot_left"]
    a_min = -25 + v["DELTA"]
    a_max = 100 + v["DELTA"]
    worst = 0.0
    for a in np.arange(a_min - 5, a_max + 5.01, 2.5):
        f = foot.rotate([0, -a, 0])          # left side: alpha toward the back = -X
        worst = max(worst, vol(boss ^ f))
    rep("left foot vs left boss, alpha_bail %.0f..%.0f (+-5)" % (a_min, a_max), worst, worst < 1.0)
    worst = 0.0
    for a in np.arange(a_min - 5, a_max + 5.01, 2.5):
        worst = max(worst, vol(M["H01R_hub_plate"] ^ M["H05R_foot_right"].rotate([0, -a, 0])))
    rep("right foot vs right boss, same sweep", worst, worst < 1.0)
    # 2. the hinge leaves themselves: dummy leaves (3 mm plates + knuckle) must not hit printed parts
    def leaf(th, sgn):
        # sgn -1: boss leaf (block toward decreasing theta); +1: foot leaf
        if sgn < 0:
            m = Manifold.cube([v["HINGE_LEAF_T"], v["R_LEAF"], v["HINGE_L"]]).translate([v["HINGE_H"] - v["HINGE_LEAF_T"] - 0.05, 0, v["Y_HINGE0"]]).rotate([0, 0, th])
        else:
            m = Manifold.cube([v["HINGE_LEAF_T"], v["R_LEAF"], v["HINGE_L"]]).translate([v["HINGE_H"] - v["HINGE_LEAF_T"] - 0.05, -v["R_LEAF"], v["Y_HINGE0"]]).rotate([0, 0, th + 180])
        return m.rotate([90, 0, 0]).mirror([0, 1, 0])          # hub-local -> H, left side
    knuckle = Manifold.cylinder(v["HINGE_L"], v["HINGE_KNUCKLE_D"] / 2, v["HINGE_KNUCKLE_D"] / 2, 32).translate(
        [0, 0, v["Y_HINGE0"]]).rotate([90, 0, 0]).mirror([0, 1, 0])
    bl = leaf(v["TH_B"], -1)
    fl = leaf(v["FOOT_LEAF_OFF"], +1)
    w1 = max(vol(foot.rotate([0, -a, 0]) ^ bl) for a in np.arange(a_min, a_max + 0.01, 2.5))
    w2 = max(vol(boss ^ fl.rotate([0, -a, 0])) for a in np.arange(a_min, a_max + 0.01, 2.5))
    w3 = vol(boss ^ (bl + knuckle)) + vol(foot ^ (fl + knuckle))
    rep("E6 leaves: foot vs boss leaf %.2f, plate vs foot leaf %.2f, own %.2f" % (w1, w2, w3), w1 + w2 + w3, w1 + w2 + w3 < 1.0)
    wl = max(vol(bl ^ fl.rotate([0, -a, 0])) for a in np.arange(a_min, a_max + 0.01, 2.5))
    rep("E6 leaves vs each other over alpha (fold range)", wl, wl < 1.0)
    # 3. foot sleeve / bail tube vs side plate and boss
    tubes0 = bail_tubes(v, 0.0)
    for nm in ("H01L_hub_plate", "H01R_hub_plate", "H04L_foot_left", "H05R_foot_right"):
        w = 0.0
        rng = np.arange(a_min, a_max + 0.01, 5) if "hub" in nm else [0.0]
        for a in rng:
            w = max(w, vol(M[nm] ^ bail_tubes(v, a)))
        rep("bail tubes vs %s over alpha" % nm, w, w < 1.0)
    # 4. carriage vs nodes / posts / tubes along beta (carriage local -> H at alpha 0)
    car = M["H10_carriage"]
    nodes = [place_node(M["H07_chord_node"], k * v["CH_DEG"], 0, v["R_BAIL"]) for k in (-2, -1, 1, 2)]
    nodes.append(place_node(M["H08a_vertex_half"], 0, 0, v["R_BAIL"]))
    nodes.append(place_node(M["H08b_vertex_half"], 0, 0, v["R_BAIL"]))
    allnodes = nodes[0]
    for n in nodes[1:]:
        allnodes = allnodes + n
    worst = 0.0
    wb = None
    for b in np.arange(-40, 40.01, 1.0):
        c = place_car(car, b, 0, v["R_SI"])
        w = vol(c ^ allnodes) + vol(c ^ tubes0)
        if w > worst:
            worst, wb = w, b
    rep("carriage vs nodes+posts+tubes, beta -40..40 step 1 (worst at %s)" % wb, worst, worst < 1.0)
    # 5. spider at full retract vs tubes, nodes, clips (alpha 0 frame; pad axis rotated by DELTA)
    spider = M["H12_spider"]
    clip = M["H16_harness_clip"]
    worst = 0.0
    wmin = 99.0
    for b in np.arange(-40, 40.01, 2.0):
        s = spider.translate([0, 0, v["RHO_SPIDER_TOP"]]).rotate([-v["DELTA"], 0, 0]).translate([0, 0, -v["R_SI"]])
        s = place_car(s, b, 0, v["R_SI"])
        w = vol(s ^ (tubes0 + allnodes))
        worst = max(worst, w)
    rep("spider (full retract) vs tubes+nodes, beta -40..40", worst, worst < 1.0)
    # clips on the right chords at mid-chord, bundle side B
    clips = None
    for k in (-3, -2, -1):
        b0, b1 = math.radians(k * v["CH_DEG"]), math.radians((k + 1) * v["CH_DEG"])
        a = np.array([0, v["R_BAIL"] * math.sin(b0), v["R_BAIL"] * math.cos(b0)])
        bb = np.array([0, v["R_BAIL"] * math.sin(b1), v["R_BAIL"] * math.cos(b1)])
        mid = (a + bb) / 2
        bm = (k + 0.5) * v["CH_DEG"]
        cm = clip.translate([-4, 0, 0]).rotate([0, 0, 180]).rotate([0, 0, 90]).rotate([-bm, 0, 0]).translate(mid.tolist())
        clips = cm if clips is None else clips + cm
    worst = 0.0
    for b in np.arange(-40, 0.01, 2.0):
        s = spider.translate([0, 0, v["RHO_SPIDER_TOP"]]).rotate([-v["DELTA"], 0, 0]).translate([0, 0, -v["R_SI"]])
        s = place_car(s, b, 0, v["R_SI"])
        c = place_car(car, b, 0, v["R_SI"])
        worst = max(worst, vol(s ^ clips) + vol(c ^ clips))
    rep("spider + carriage vs harness clips (right chords), beta -40..0", worst, worst < 1.0)
    # 6. clearances (numbers)
    rt_mid = v["R_BAIL"] * math.cos(math.radians(v["CH_DEG"] / 2))
    rep("spider top at full retract below tube bottom (mid-chord)", rt_mid - 4 - v["RHO_SPIDER_TOP"], rt_mid - 4 - v["RHO_SPIDER_TOP"] >= 2.9, "mm")
    rep("ear: boss/side-plate cut above ear top (EAR_CUT_Z - EAR_TOP_Z)", v["EAR_CUT_Z"] - v["EAR_TOP_Z"], v["EAR_CUT_Z"] - v["EAR_TOP_Z"] >= 4, "mm")
    rep("ear: side plate inboard face outboard of ear rim (Y_SIDE_IN - EAR_OUT_Y)", v["Y_SIDE_IN"] - v["EAR_OUT_Y"], True, "mm")
    rep("hub axis to ear canal distance (red line 6 >= 25)", math.hypot(0 - v["TRAG_X"], 45), math.hypot(v["TRAG_X"], 45) >= 25, "mm")
    rep("hinge fold: min angle between leaves (deg, >= 45)", (a_min) - v["TH_B"], (a_min) - v["TH_B"] >= 45, "deg")
    rep("hinge fold: max angle between leaves (deg, <= 180)", (a_max) - v["TH_B"], (a_max) - v["TH_B"] <= 180, "deg")
    return ok


if __name__ == "__main__":
    sys.exit(main())
