// H01L_hub_plate  (qty 1; frame: H; MJF PA12; print service OK (stops are adjustable))
// GENERATED by gen_halo_stl.py from halo_parts.py. Change numbers in halo_params.scad.
// Every dimension below is an expression of the names in halo_params.scad.
include <../halo_params.scad>

mirror([0, 1, 0]) {
    rotate([90, 0, 0]) {
        difference() {
            union() {
                translate([0, 0, Y_SIDE_IN]) {
                    cylinder(h = SIDE_T, r = R_HUBDISC, center = false, $fn = 96);
                }
                translate([26, BAND_Z_SIDE - 12, Y_SIDE_IN - 5.5]) {
                    cube([30, BAND_Z_SIDE + 12 - (BAND_Z_SIDE - 12), Y_SIDE_IN + 1 - (Y_SIDE_IN - 5.5)], center = false);
                }
                hull() {
                    translate([16, 3, Y_SIDE_IN]) {
                        cylinder(h = STOP_RING_T, r = 8, center = false, $fn = 48);
                    }
                    translate([30, BAND_Z_SIDE - 12, Y_SIDE_IN]) {
                        cube([26, BAND_Z_SIDE + 12 - (BAND_Z_SIDE - 12), Y_SIDE_IN + 1 - Y_SIDE_IN], center = false);
                    }
                }
                translate([-46, -9.5, Y_SIDE_IN]) {
                    cube([24, 7, Y_SIDE_IN + STOP_RING_T - Y_SIDE_IN], center = false);
                }
                translate([0, 0, Y_SIDE_IN]) {
                    rotate([0, 0, STOP_FRONT0 + 90]) {
                        rotate_extrude(angle = STOP_FRONT1 - STOP_FRONT0, $fn = 96) polygon([[R_HUBDISC - 1, 0], [R_STOP1, 0], [R_STOP1, Y_SIDE_IN + STOP_RING_T - Y_SIDE_IN], [R_HUBDISC - 1, Y_SIDE_IN + STOP_RING_T - Y_SIDE_IN]]);
                    }
                }
                translate([0, 0, Y_SIDE_IN]) {
                    rotate([0, 0, STOP_REAR0 + 90]) {
                        rotate_extrude(angle = STOP_REAR1 - STOP_REAR0, $fn = 96) polygon([[R_HUBDISC - 1, 0], [R_STOP1, 0], [R_STOP1, Y_SIDE_IN + STOP_RING_T - Y_SIDE_IN], [R_HUBDISC - 1, Y_SIDE_IN + STOP_RING_T - Y_SIDE_IN]]);
                    }
                }
                rotate([0, 0, TH_B]) {
                    translate([HINGE_H, 2, Y_SIDE_IN]) {
                        cube([HINGE_H + HINGE_SEAT_T - HINGE_H, R_LEAF + 1.75 - 2, Y_HINGE1 - Y_SIDE_IN], center = false);
                    }
                }
            }
            translate([-60, -70, Y_SIDE_IN - 7]) {
                cube([65, EAR_CUT_Z - -70, Y_F1 + 0.5 - (Y_SIDE_IN - 7)], center = false);
            }
            rotate([0, 0, TH_B]) {
                translate([HINGE_H - 0.01, HINGE_STUD_X, (Y_HINGE0 + Y_HINGE1) / 2 + -1 * HINGE_STUD_Y]) {
                    rotate([0, 90, 0]) {
                        cylinder(h = M4_INS_L + 0.01, r = M4_INS_D / 2, center = false, $fn = 24);
                    }
                }
            }
            rotate([0, 0, TH_B]) {
                translate([HINGE_H - 0.01, HINGE_STUD_X, (Y_HINGE0 + Y_HINGE1) / 2 + 1 * HINGE_STUD_Y]) {
                    rotate([0, 90, 0]) {
                        cylinder(h = M4_INS_L + 0.01, r = M4_INS_D / 2, center = false, $fn = 24);
                    }
                }
            }
            translate([28, BAND_Z_SIDE - 10.3, Y_SIDE_IN - 2.25 - 0.7]) {
                cube([28.1, BAND_Z_SIDE + 10.3 - (BAND_Z_SIDE - 10.3), Y_SIDE_IN - 2.25 + 0.7 - (Y_SIDE_IN - 2.25 - 0.7)], center = false);
            }
            translate([51, BAND_Z_SIDE, Y_SIDE_IN - 7]) {
                cylinder(h = 10, r = M3_CLEAR / 2, center = false, $fn = 20);
            }
            translate([-40, -6, Y_SIDE_IN - 0.01]) {
                cylinder(h = STOP_RING_T + 0.02, r = M3_INS_D / 2, center = false, $fn = 20);
            }
            translate([-29, -6, Y_SIDE_IN - 0.01]) {
                cylinder(h = STOP_RING_T + 0.02, r = M3_INS_D / 2, center = false, $fn = 20);
            }
            translate([0, 0, Y_F1]) {
                rotate([0, 0, -45 + DELTA + DET_ARM_OFF + 90]) {
                    translate([R_DET, 0, 0]) {
                        rotate([45, 0, 0]) {
                            cube([4, NOTCH_D * 1.414214, NOTCH_D * 1.414214], center = true);
                        }
                    }
                }
            }
            translate([0, 0, Y_F1]) {
                rotate([0, 0, -30 + DELTA + DET_ARM_OFF + 90]) {
                    translate([R_DET, 0, 0]) {
                        rotate([45, 0, 0]) {
                            cube([4, NOTCH_D * 1.414214, NOTCH_D * 1.414214], center = true);
                        }
                    }
                }
            }
            translate([0, 0, Y_F1]) {
                rotate([0, 0, -15 + DELTA + DET_ARM_OFF + 90]) {
                    translate([R_DET, 0, 0]) {
                        rotate([45, 0, 0]) {
                            cube([4, NOTCH_D * 1.414214, NOTCH_D * 1.414214], center = true);
                        }
                    }
                }
            }
            translate([0, 0, Y_F1]) {
                rotate([0, 0, 0 + DELTA + DET_ARM_OFF + 90]) {
                    translate([R_DET, 0, 0]) {
                        rotate([45, 0, 0]) {
                            cube([4, NOTCH_D * 1.414214, NOTCH_D * 1.414214], center = true);
                        }
                    }
                }
            }
            translate([0, 0, Y_F1]) {
                rotate([0, 0, 15 + DELTA + DET_ARM_OFF + 90]) {
                    translate([R_DET, 0, 0]) {
                        rotate([45, 0, 0]) {
                            cube([4, NOTCH_D * 1.414214, NOTCH_D * 1.414214], center = true);
                        }
                    }
                }
            }
            translate([0, 0, Y_F1]) {
                rotate([0, 0, 30 + DELTA + DET_ARM_OFF + 90]) {
                    translate([R_DET, 0, 0]) {
                        rotate([45, 0, 0]) {
                            cube([4, NOTCH_D * 1.414214, NOTCH_D * 1.414214], center = true);
                        }
                    }
                }
            }
            translate([0, 0, Y_F1]) {
                rotate([0, 0, 45 + DELTA + DET_ARM_OFF + 90]) {
                    translate([R_DET, 0, 0]) {
                        rotate([45, 0, 0]) {
                            cube([4, NOTCH_D * 1.414214, NOTCH_D * 1.414214], center = true);
                        }
                    }
                }
            }
            translate([0, 0, Y_F1]) {
                rotate([0, 0, 60 + DELTA + DET_ARM_OFF + 90]) {
                    translate([R_DET, 0, 0]) {
                        rotate([45, 0, 0]) {
                            cube([4, NOTCH_D * 1.414214, NOTCH_D * 1.414214], center = true);
                        }
                    }
                }
            }
            translate([0, 0, Y_F1]) {
                rotate([0, 0, 75 + DELTA + DET_ARM_OFF + 90]) {
                    translate([R_DET, 0, 0]) {
                        rotate([45, 0, 0]) {
                            cube([4, NOTCH_D * 1.414214, NOTCH_D * 1.414214], center = true);
                        }
                    }
                }
            }
            translate([0, 0, Y_F1]) {
                rotate([0, 0, 90 + DELTA + DET_ARM_OFF + 90]) {
                    translate([R_DET, 0, 0]) {
                        rotate([45, 0, 0]) {
                            cube([4, NOTCH_D * 1.414214, NOTCH_D * 1.414214], center = true);
                        }
                    }
                }
            }
            translate([0, 0, Y_F1]) {
                rotate([0, 0, 105 + DELTA + DET_ARM_OFF + 90]) {
                    translate([R_DET, 0, 0]) {
                        rotate([45, 0, 0]) {
                            cube([4, NOTCH_D * 1.414214, NOTCH_D * 1.414214], center = true);
                        }
                    }
                }
            }
            translate([0, 0, Y_SIDE_IN - 1]) {
                rotate([0, 0, STOP_FRONT0 + 5 + 90]) {
                    rotate_extrude(angle = STOP_FRONT1 - 5 - (STOP_FRONT0 + 5), $fn = 96) polygon([[R_STOP_SLOT - 1.7, 0], [R_STOP_SLOT + 1.7, 0], [R_STOP_SLOT + 1.7, Y_SIDE_IN + STOP_RING_T + 1 - (Y_SIDE_IN - 1)], [R_STOP_SLOT - 1.7, Y_SIDE_IN + STOP_RING_T + 1 - (Y_SIDE_IN - 1)]]);
                }
            }
            translate([0, 0, Y_SIDE_IN - 1]) {
                rotate([0, 0, STOP_REAR0 + 5 + 90]) {
                    rotate_extrude(angle = STOP_REAR1 - 5 - (STOP_REAR0 + 5), $fn = 96) polygon([[R_STOP_SLOT - 1.7, 0], [R_STOP_SLOT + 1.7, 0], [R_STOP_SLOT + 1.7, Y_SIDE_IN + STOP_RING_T + 1 - (Y_SIDE_IN - 1)], [R_STOP_SLOT - 1.7, Y_SIDE_IN + STOP_RING_T + 1 - (Y_SIDE_IN - 1)]]);
                }
            }
            translate([(-R_STOP_PIN) * -0.984808, R_STOP_PIN * -0.173648, Y_SIDE_IN - 1]) {
                cylinder(h = STOP_RING_T + 2, r = 1.55, center = false, $fn = 20);
            }
            translate([(-R_STOP_PIN) * -1, R_STOP_PIN * 0, Y_SIDE_IN - 1]) {
                cylinder(h = STOP_RING_T + 2, r = 1.55, center = false, $fn = 20);
            }
            translate([(-R_STOP_PIN) * -0.984808, R_STOP_PIN * 0.173648, Y_SIDE_IN - 1]) {
                cylinder(h = STOP_RING_T + 2, r = 1.55, center = false, $fn = 20);
            }
            translate([(-R_STOP_PIN) * -0.939693, R_STOP_PIN * 0.34202, Y_SIDE_IN - 1]) {
                cylinder(h = STOP_RING_T + 2, r = 1.55, center = false, $fn = 20);
            }
            translate([(-R_STOP_PIN) * -0.866025, R_STOP_PIN * 0.5, Y_SIDE_IN - 1]) {
                cylinder(h = STOP_RING_T + 2, r = 1.55, center = false, $fn = 20);
            }
            translate([(-R_STOP_PIN) * -0.766044, R_STOP_PIN * 0.642788, Y_SIDE_IN - 1]) {
                cylinder(h = STOP_RING_T + 2, r = 1.55, center = false, $fn = 20);
            }
            translate([(-R_STOP_PIN) * 0.766044, R_STOP_PIN * 0.642788, Y_SIDE_IN - 1]) {
                cylinder(h = STOP_RING_T + 2, r = 1.55, center = false, $fn = 20);
            }
            translate([(-R_STOP_PIN) * 0.866025, R_STOP_PIN * 0.5, Y_SIDE_IN - 1]) {
                cylinder(h = STOP_RING_T + 2, r = 1.55, center = false, $fn = 20);
            }
            translate([(-R_STOP_PIN) * 0.939693, R_STOP_PIN * 0.34202, Y_SIDE_IN - 1]) {
                cylinder(h = STOP_RING_T + 2, r = 1.55, center = false, $fn = 20);
            }
            translate([(-R_STOP_PIN) * 0.984808, R_STOP_PIN * 0.173648, Y_SIDE_IN - 1]) {
                cylinder(h = STOP_RING_T + 2, r = 1.55, center = false, $fn = 20);
            }
            translate([(-R_STOP_PIN) * 1, R_STOP_PIN * 0, Y_SIDE_IN - 1]) {
                cylinder(h = STOP_RING_T + 2, r = 1.55, center = false, $fn = 20);
            }
        }
    }
}
