// H05R_foot_right  (qty 1; frame: H at alpha_bail 0; MJF PA12; print service OK)
// GENERATED by gen_halo_stl.py from halo_parts.py. Change numbers in halo_params.scad.
// Every dimension below is an expression of the names in halo_params.scad.
include <../halo_params.scad>

rotate([90, 0, 0]) {
    difference() {
        union() {
            union() {
                rotate([0, 0, FOOT_LEAF_OFF + 180]) {
                    translate([HINGE_H, -(R_LEAF + 1.75), Y_HINGE0 + 0.5]) {
                        cube([HINGE_H + HINGE_SEAT_T - HINGE_H, -2 - (-(R_LEAF + 1.75)), Y_HINGE1 + 4.5 - (Y_HINGE0 + 0.5)], center = false);
                    }
                }
                hull() {
                    translate([0, 0, Y_HINGE1 + 0.5]) {
                        cylinder(h = Y_HINGE1 + 4.5 - (Y_HINGE1 + 0.5), r = 8, center = false, $fn = 48);
                    }
                    rotate([0, 0, FOOT_LEAF_OFF + 180]) {
                        translate([HINGE_H, -(R_LEAF + 1.75), Y_HINGE1 + 0.5]) {
                            cube([HINGE_H + HINGE_SEAT_T - HINGE_H, -2 - (-(R_LEAF + 1.75)), Y_HINGE1 + 4.5 - (Y_HINGE1 + 0.5)], center = false);
                        }
                    }
                }
                translate([0 + (LEG_T0 - 2) * 0, 0 + (LEG_T0 - 2) * LEG_DZ, Y_HUB + (LEG_T0 - 2) * LEG_DY]) {
                    rotate([0, acos((Y_HUB + (LEG_T0 + SOCK_DEPTH) * LEG_DY - (Y_HUB + (LEG_T0 - 2) * LEG_DY)) / sqrt((0 + (LEG_T0 + SOCK_DEPTH) * 0 - (0 + (LEG_T0 - 2) * 0)) * (0 + (LEG_T0 + SOCK_DEPTH) * 0 - (0 + (LEG_T0 - 2) * 0)) + (0 + (LEG_T0 + SOCK_DEPTH) * LEG_DZ - (0 + (LEG_T0 - 2) * LEG_DZ)) * (0 + (LEG_T0 + SOCK_DEPTH) * LEG_DZ - (0 + (LEG_T0 - 2) * LEG_DZ)) + (Y_HUB + (LEG_T0 + SOCK_DEPTH) * LEG_DY - (Y_HUB + (LEG_T0 - 2) * LEG_DY)) * (Y_HUB + (LEG_T0 + SOCK_DEPTH) * LEG_DY - (Y_HUB + (LEG_T0 - 2) * LEG_DY)))), atan2(0 + (LEG_T0 + SOCK_DEPTH) * LEG_DZ - (0 + (LEG_T0 - 2) * LEG_DZ), 0 + (LEG_T0 + SOCK_DEPTH) * 0 - (0 + (LEG_T0 - 2) * 0))]) {
                        cylinder(h = sqrt((0 + (LEG_T0 + SOCK_DEPTH) * 0 - (0 + (LEG_T0 - 2) * 0)) * (0 + (LEG_T0 + SOCK_DEPTH) * 0 - (0 + (LEG_T0 - 2) * 0)) + (0 + (LEG_T0 + SOCK_DEPTH) * LEG_DZ - (0 + (LEG_T0 - 2) * LEG_DZ)) * (0 + (LEG_T0 + SOCK_DEPTH) * LEG_DZ - (0 + (LEG_T0 - 2) * LEG_DZ)) + (Y_HUB + (LEG_T0 + SOCK_DEPTH) * LEG_DY - (Y_HUB + (LEG_T0 - 2) * LEG_DY)) * (Y_HUB + (LEG_T0 + SOCK_DEPTH) * LEG_DY - (Y_HUB + (LEG_T0 - 2) * LEG_DY))), r = SOCK_D / 2 + SOCK_WALL, center = false, $fn = 48);
                    }
                }
                hull() {
                    translate([0, 0, Y_HINGE1 + 0.5]) {
                        cylinder(h = Y_HINGE1 + 4.5 - (Y_HINGE1 + 0.5), r = 8, center = false, $fn = 48);
                    }
                    translate([0 + (LEG_T0 - 2) * 0, 0 + (LEG_T0 - 2) * LEG_DZ, Y_HUB + (LEG_T0 - 2) * LEG_DY]) {
                        rotate([0, acos((Y_HUB + (LEG_T0 + 3) * LEG_DY - (Y_HUB + (LEG_T0 - 2) * LEG_DY)) / sqrt((0 + (LEG_T0 + 3) * 0 - (0 + (LEG_T0 - 2) * 0)) * (0 + (LEG_T0 + 3) * 0 - (0 + (LEG_T0 - 2) * 0)) + (0 + (LEG_T0 + 3) * LEG_DZ - (0 + (LEG_T0 - 2) * LEG_DZ)) * (0 + (LEG_T0 + 3) * LEG_DZ - (0 + (LEG_T0 - 2) * LEG_DZ)) + (Y_HUB + (LEG_T0 + 3) * LEG_DY - (Y_HUB + (LEG_T0 - 2) * LEG_DY)) * (Y_HUB + (LEG_T0 + 3) * LEG_DY - (Y_HUB + (LEG_T0 - 2) * LEG_DY)))), atan2(0 + (LEG_T0 + 3) * LEG_DZ - (0 + (LEG_T0 - 2) * LEG_DZ), 0 + (LEG_T0 + 3) * 0 - (0 + (LEG_T0 - 2) * 0))]) {
                            cylinder(h = sqrt((0 + (LEG_T0 + 3) * 0 - (0 + (LEG_T0 - 2) * 0)) * (0 + (LEG_T0 + 3) * 0 - (0 + (LEG_T0 - 2) * 0)) + (0 + (LEG_T0 + 3) * LEG_DZ - (0 + (LEG_T0 - 2) * LEG_DZ)) * (0 + (LEG_T0 + 3) * LEG_DZ - (0 + (LEG_T0 - 2) * LEG_DZ)) + (Y_HUB + (LEG_T0 + 3) * LEG_DY - (Y_HUB + (LEG_T0 - 2) * LEG_DY)) * (Y_HUB + (LEG_T0 + 3) * LEG_DY - (Y_HUB + (LEG_T0 - 2) * LEG_DY))), r = SOCK_D / 2 + SOCK_WALL, center = false, $fn = 48);
                        }
                    }
                }
                translate([0, 0, Y_F1 + BOSS_T + 0.5]) {
                    rotate([0, 0, 95]) {
                        rotate_extrude(angle = 40, $fn = 96) polygon([[R_LEAFC, 0], [R_LEAFC + 6, 0], [R_LEAFC + 6, Y_F1 + BOSS_T + 0.5 + 8 - (Y_F1 + BOSS_T + 0.5)], [R_LEAFC, Y_F1 + BOSS_T + 0.5 + 8 - (Y_F1 + BOSS_T + 0.5)]]);
                    }
                }
            }
            translate([0, 0, Y_HINGE1 + 4.5 - 0.01]) {
                cylinder(h = 12, r = SOCK_D / 2 + SOCK_WALL, center = false, $fn = 48);
            }
        }
        rotate([0, 0, FOOT_LEAF_OFF + 180]) {
            translate([HINGE_H - 0.01, -HINGE_STUD_X, (Y_HINGE0 + Y_HINGE1) / 2 + -1 * HINGE_STUD_Y]) {
                rotate([0, 90, 0]) {
                    cylinder(h = M4_INS_L + 0.01, r = M4_INS_D / 2, center = false, $fn = 24);
                }
            }
        }
        rotate([0, 0, FOOT_LEAF_OFF + 180]) {
            translate([HINGE_H - 0.01, -HINGE_STUD_X, (Y_HINGE0 + Y_HINGE1) / 2 + 1 * HINGE_STUD_Y]) {
                rotate([0, 90, 0]) {
                    cylinder(h = M4_INS_L + 0.01, r = M4_INS_D / 2, center = false, $fn = 24);
                }
            }
        }
        translate([0 + LEG_T0 * 0, 0 + LEG_T0 * LEG_DZ, Y_HUB + LEG_T0 * LEG_DY]) {
            rotate([0, acos((Y_HUB + (LEG_T0 + SOCK_DEPTH + 0.1) * LEG_DY - (Y_HUB + LEG_T0 * LEG_DY)) / sqrt((0 + (LEG_T0 + SOCK_DEPTH + 0.1) * 0 - (0 + LEG_T0 * 0)) * (0 + (LEG_T0 + SOCK_DEPTH + 0.1) * 0 - (0 + LEG_T0 * 0)) + (0 + (LEG_T0 + SOCK_DEPTH + 0.1) * LEG_DZ - (0 + LEG_T0 * LEG_DZ)) * (0 + (LEG_T0 + SOCK_DEPTH + 0.1) * LEG_DZ - (0 + LEG_T0 * LEG_DZ)) + (Y_HUB + (LEG_T0 + SOCK_DEPTH + 0.1) * LEG_DY - (Y_HUB + LEG_T0 * LEG_DY)) * (Y_HUB + (LEG_T0 + SOCK_DEPTH + 0.1) * LEG_DY - (Y_HUB + LEG_T0 * LEG_DY)))), atan2(0 + (LEG_T0 + SOCK_DEPTH + 0.1) * LEG_DZ - (0 + LEG_T0 * LEG_DZ), 0 + (LEG_T0 + SOCK_DEPTH + 0.1) * 0 - (0 + LEG_T0 * 0))]) {
                cylinder(h = sqrt((0 + (LEG_T0 + SOCK_DEPTH + 0.1) * 0 - (0 + LEG_T0 * 0)) * (0 + (LEG_T0 + SOCK_DEPTH + 0.1) * 0 - (0 + LEG_T0 * 0)) + (0 + (LEG_T0 + SOCK_DEPTH + 0.1) * LEG_DZ - (0 + LEG_T0 * LEG_DZ)) * (0 + (LEG_T0 + SOCK_DEPTH + 0.1) * LEG_DZ - (0 + LEG_T0 * LEG_DZ)) + (Y_HUB + (LEG_T0 + SOCK_DEPTH + 0.1) * LEG_DY - (Y_HUB + LEG_T0 * LEG_DY)) * (Y_HUB + (LEG_T0 + SOCK_DEPTH + 0.1) * LEG_DY - (Y_HUB + LEG_T0 * LEG_DY))), r = SOCK_D / 2, center = false, $fn = 48);
            }
        }
        translate([0 + (LEG_T0 + SOCK_DEPTH - 0.6) * 0, 0 + (LEG_T0 + SOCK_DEPTH - 0.6) * LEG_DZ, Y_HUB + (LEG_T0 + SOCK_DEPTH - 0.6) * LEG_DY]) {
            rotate([0, acos((Y_HUB + (LEG_T0 + SOCK_DEPTH + 0.01) * LEG_DY - (Y_HUB + (LEG_T0 + SOCK_DEPTH - 0.6) * LEG_DY)) / sqrt((0 + (LEG_T0 + SOCK_DEPTH + 0.01) * 0 - (0 + (LEG_T0 + SOCK_DEPTH - 0.6) * 0)) * (0 + (LEG_T0 + SOCK_DEPTH + 0.01) * 0 - (0 + (LEG_T0 + SOCK_DEPTH - 0.6) * 0)) + (0 + (LEG_T0 + SOCK_DEPTH + 0.01) * LEG_DZ - (0 + (LEG_T0 + SOCK_DEPTH - 0.6) * LEG_DZ)) * (0 + (LEG_T0 + SOCK_DEPTH + 0.01) * LEG_DZ - (0 + (LEG_T0 + SOCK_DEPTH - 0.6) * LEG_DZ)) + (Y_HUB + (LEG_T0 + SOCK_DEPTH + 0.01) * LEG_DY - (Y_HUB + (LEG_T0 + SOCK_DEPTH - 0.6) * LEG_DY)) * (Y_HUB + (LEG_T0 + SOCK_DEPTH + 0.01) * LEG_DY - (Y_HUB + (LEG_T0 + SOCK_DEPTH - 0.6) * LEG_DY)))), atan2(0 + (LEG_T0 + SOCK_DEPTH + 0.01) * LEG_DZ - (0 + (LEG_T0 + SOCK_DEPTH - 0.6) * LEG_DZ), 0 + (LEG_T0 + SOCK_DEPTH + 0.01) * 0 - (0 + (LEG_T0 + SOCK_DEPTH - 0.6) * 0))]) {
                cylinder(h = sqrt((0 + (LEG_T0 + SOCK_DEPTH + 0.01) * 0 - (0 + (LEG_T0 + SOCK_DEPTH - 0.6) * 0)) * (0 + (LEG_T0 + SOCK_DEPTH + 0.01) * 0 - (0 + (LEG_T0 + SOCK_DEPTH - 0.6) * 0)) + (0 + (LEG_T0 + SOCK_DEPTH + 0.01) * LEG_DZ - (0 + (LEG_T0 + SOCK_DEPTH - 0.6) * LEG_DZ)) * (0 + (LEG_T0 + SOCK_DEPTH + 0.01) * LEG_DZ - (0 + (LEG_T0 + SOCK_DEPTH - 0.6) * LEG_DZ)) + (Y_HUB + (LEG_T0 + SOCK_DEPTH + 0.01) * LEG_DY - (Y_HUB + (LEG_T0 + SOCK_DEPTH - 0.6) * LEG_DY)) * (Y_HUB + (LEG_T0 + SOCK_DEPTH + 0.01) * LEG_DY - (Y_HUB + (LEG_T0 + SOCK_DEPTH - 0.6) * LEG_DY))), r1 = SOCK_D / 2, r2 = SOCK_D / 2 + 0.6, center = false, $fn = 48);
            }
        }
        translate([0, 0, Y_HINGE0 + 0.5 - 1]) {
            cylinder(h = Y_HINGE1 - (Y_HINGE0 + 0.5) + 1, r = HINGE_KNUCKLE_D / 2 + 0.4, center = false, $fn = 32);
        }
        translate([(-((R_BRAKE0 + R_BRAKE1) / 2)) * sin(BRAKE_TH), ((R_BRAKE0 + R_BRAKE1) / 2) * cos(BRAKE_TH), Y_F1 + BOSS_T + 0.5 - 0.01]) {
            cylinder(h = 5.01, r = 1.75, center = false, $fn = 20);
        }
        translate([(-((R_BRAKE0 + R_BRAKE1) / 2)) * sin(BRAKE_TH), ((R_BRAKE0 + R_BRAKE1) / 2) * cos(BRAKE_TH), Y_F1 + BOSS_T + 0.5 + 8 - M3_INS_L]) {
            cylinder(h = M3_INS_L + 0.01, r = M3_INS_D / 2, center = false, $fn = 20);
        }
        translate([(-((R_BRAKE0 + R_BRAKE1) / 2)) * sin(BRAKE_TH), ((R_BRAKE0 + R_BRAKE1) / 2) * cos(BRAKE_TH), Y_F1 + BOSS_T + 0.5 + 4.9]) {
            cylinder(h = Y_F1 + BOSS_T + 0.5 + 8 - (Y_F1 + BOSS_T + 0.5), r = 1.7, center = false, $fn = 20);
        }
        translate([0, 0, Y_HINGE1 + 4.5 - 0.01 + 1]) {
            cylinder(h = 11.1, r = SOCK_D / 2, center = false, $fn = 48);
        }
    }
}
