// H06_alpha_stop  (qty 2; frame: local; MJF PA12; print service OK)
// GENERATED by gen_halo_stl.py from halo_parts.py. Change numbers in halo_params.scad.
// Every dimension below is an expression of the names in halo_params.scad.
include <../halo_params.scad>

difference() {
    linear_extrude(height = 6, center = false) polygon([[R_STOP1 - 1 - 1.2 + 0, -7], [R_STOP1 - 1 - 1.2 + 0.45922, -6.908655], [R_STOP1 - 1 - 1.2 + 0.848528, -6.648528], [R_STOP1 - 1 - 1.2 + 1.108655, -6.25922], [R_STOP1 - 1 - 1.2 + 1.2, -5.8], [R_STOP1 - 1 - 1.2 + 1.2, 5.8], [R_STOP1 - 1 - 1.2 + 1.108655, 6.25922], [R_STOP1 - 1 - 1.2 + 0.848528, 6.648528], [R_STOP1 - 1 - 1.2 + 0.45922, 6.908655], [R_STOP1 - 1 - 1.2 + 0, 7], [R_STOP0 + 1 + 1.2 + 0, 7], [R_STOP0 + 1 + 1.2 + -0.45922, 6.908655], [R_STOP0 + 1 + 1.2 + -0.848528, 6.648528], [R_STOP0 + 1 + 1.2 + -1.108655, 6.25922], [R_STOP0 + 1 + 1.2 + -1.2, 5.8], [R_STOP0 + 1 + 1.2 + -1.2, -5.8], [R_STOP0 + 1 + 1.2 + -1.108655, -6.25922], [R_STOP0 + 1 + 1.2 + -0.848528, -6.648528], [R_STOP0 + 1 + 1.2 + -0.45922, -6.908655], [R_STOP0 + 1 + 1.2 + 0, -7]]);
    translate([R_STOP_SLOT, 0, -0.01]) {
        cylinder(h = M3_INS_L + 0.01, r = M3_INS_D / 2, center = false, $fn = 24);
    }
    translate([R_STOP_PIN * 0.991445, (-1 * R_STOP_PIN) * 0.130526, -0.01]) {
        cylinder(h = 4.01, r = 1.55, center = false, $fn = 20);
    }
    translate([R_STOP_PIN * 0.991445, (1 * R_STOP_PIN) * 0.130526, -0.01]) {
        cylinder(h = 4.01, r = 1.55, center = false, $fn = 20);
    }
}
