// H08b_vertex_half  (qty 1; frame: node; MJF PA12; print service OK)
// GENERATED by gen_halo_stl.py from halo_parts.py. Change numbers in halo_params.scad.
// Every dimension below is an expression of the names in halo_params.scad.
include <../halo_params.scad>

difference() {
    union() {
        translate([0, 0, 0]) {
            rotate([0, acos(((SOCK_BOT + SOCK_DEPTH) * (-sin(CH_DEG / 2)) - 0) / sqrt(((SOCK_BOT + SOCK_DEPTH) * (-1 * cos(CH_DEG / 2)) - 0) * ((SOCK_BOT + SOCK_DEPTH) * (-1 * cos(CH_DEG / 2)) - 0) + ((SOCK_BOT + SOCK_DEPTH) * 0 - 0) * ((SOCK_BOT + SOCK_DEPTH) * 0 - 0) + ((SOCK_BOT + SOCK_DEPTH) * (-sin(CH_DEG / 2)) - 0) * ((SOCK_BOT + SOCK_DEPTH) * (-sin(CH_DEG / 2)) - 0))), atan2((SOCK_BOT + SOCK_DEPTH) * 0 - 0, (SOCK_BOT + SOCK_DEPTH) * (-1 * cos(CH_DEG / 2)) - 0)]) {
                cylinder(h = sqrt(((SOCK_BOT + SOCK_DEPTH) * (-1 * cos(CH_DEG / 2)) - 0) * ((SOCK_BOT + SOCK_DEPTH) * (-1 * cos(CH_DEG / 2)) - 0) + ((SOCK_BOT + SOCK_DEPTH) * 0 - 0) * ((SOCK_BOT + SOCK_DEPTH) * 0 - 0) + ((SOCK_BOT + SOCK_DEPTH) * (-sin(CH_DEG / 2)) - 0) * ((SOCK_BOT + SOCK_DEPTH) * (-sin(CH_DEG / 2)) - 0)), r = SOCK_D / 2 + SOCK_WALL, center = false, $fn = 48);
            }
        }
        intersection() {
            sphere(r = SOCK_D / 2 + SOCK_WALL, $fn = 32);
            translate([-10, -10, -10]) {
                cube([10, 20, 20], center = false);
            }
        }
        translate([-3, -12, -6]) {
            cube([3, 24, 8], center = false);
        }
        intersection() {
            hull() {
                translate([-4, -POST_N1, 2]) {
                    cube([4, -POST_N0 - (-POST_N1), TUBE_OD / 2 + POST_H - 2], center = false);
                }
                translate([-6, -POST_N1, 2]) {
                    cube([8, -POST_N0 - (-POST_N1), 2], center = false);
                }
            }
            translate([-20, -20, -5]) {
                cube([20, 40, 35], center = false);
            }
        }
        translate([-8, 9, -6]) {
            cube([6, 10, 4], center = false);
        }
    }
    translate([SOCK_BOT * (-1 * cos(CH_DEG / 2)), SOCK_BOT * 0, SOCK_BOT * (-sin(CH_DEG / 2))]) {
        rotate([0, acos(((SOCK_BOT + SOCK_DEPTH + 0.1) * (-sin(CH_DEG / 2)) - (SOCK_BOT * (-sin(CH_DEG / 2)))) / sqrt(((SOCK_BOT + SOCK_DEPTH + 0.1) * (-1 * cos(CH_DEG / 2)) - (SOCK_BOT * (-1 * cos(CH_DEG / 2)))) * ((SOCK_BOT + SOCK_DEPTH + 0.1) * (-1 * cos(CH_DEG / 2)) - (SOCK_BOT * (-1 * cos(CH_DEG / 2)))) + ((SOCK_BOT + SOCK_DEPTH + 0.1) * 0 - (SOCK_BOT * 0)) * ((SOCK_BOT + SOCK_DEPTH + 0.1) * 0 - (SOCK_BOT * 0)) + ((SOCK_BOT + SOCK_DEPTH + 0.1) * (-sin(CH_DEG / 2)) - (SOCK_BOT * (-sin(CH_DEG / 2)))) * ((SOCK_BOT + SOCK_DEPTH + 0.1) * (-sin(CH_DEG / 2)) - (SOCK_BOT * (-sin(CH_DEG / 2)))))), atan2((SOCK_BOT + SOCK_DEPTH + 0.1) * 0 - (SOCK_BOT * 0), (SOCK_BOT + SOCK_DEPTH + 0.1) * (-1 * cos(CH_DEG / 2)) - (SOCK_BOT * (-1 * cos(CH_DEG / 2))))]) {
            cylinder(h = sqrt(((SOCK_BOT + SOCK_DEPTH + 0.1) * (-1 * cos(CH_DEG / 2)) - (SOCK_BOT * (-1 * cos(CH_DEG / 2)))) * ((SOCK_BOT + SOCK_DEPTH + 0.1) * (-1 * cos(CH_DEG / 2)) - (SOCK_BOT * (-1 * cos(CH_DEG / 2)))) + ((SOCK_BOT + SOCK_DEPTH + 0.1) * 0 - (SOCK_BOT * 0)) * ((SOCK_BOT + SOCK_DEPTH + 0.1) * 0 - (SOCK_BOT * 0)) + ((SOCK_BOT + SOCK_DEPTH + 0.1) * (-sin(CH_DEG / 2)) - (SOCK_BOT * (-sin(CH_DEG / 2)))) * ((SOCK_BOT + SOCK_DEPTH + 0.1) * (-sin(CH_DEG / 2)) - (SOCK_BOT * (-sin(CH_DEG / 2))))), r = SOCK_D / 2, center = false, $fn = 48);
        }
    }
    translate([(SOCK_BOT + SOCK_DEPTH - 0.6) * (-1 * cos(CH_DEG / 2)), (SOCK_BOT + SOCK_DEPTH - 0.6) * 0, (SOCK_BOT + SOCK_DEPTH - 0.6) * (-sin(CH_DEG / 2))]) {
        rotate([0, acos(((SOCK_BOT + SOCK_DEPTH + 0.01) * (-sin(CH_DEG / 2)) - ((SOCK_BOT + SOCK_DEPTH - 0.6) * (-sin(CH_DEG / 2)))) / sqrt(((SOCK_BOT + SOCK_DEPTH + 0.01) * (-1 * cos(CH_DEG / 2)) - ((SOCK_BOT + SOCK_DEPTH - 0.6) * (-1 * cos(CH_DEG / 2)))) * ((SOCK_BOT + SOCK_DEPTH + 0.01) * (-1 * cos(CH_DEG / 2)) - ((SOCK_BOT + SOCK_DEPTH - 0.6) * (-1 * cos(CH_DEG / 2)))) + ((SOCK_BOT + SOCK_DEPTH + 0.01) * 0 - ((SOCK_BOT + SOCK_DEPTH - 0.6) * 0)) * ((SOCK_BOT + SOCK_DEPTH + 0.01) * 0 - ((SOCK_BOT + SOCK_DEPTH - 0.6) * 0)) + ((SOCK_BOT + SOCK_DEPTH + 0.01) * (-sin(CH_DEG / 2)) - ((SOCK_BOT + SOCK_DEPTH - 0.6) * (-sin(CH_DEG / 2)))) * ((SOCK_BOT + SOCK_DEPTH + 0.01) * (-sin(CH_DEG / 2)) - ((SOCK_BOT + SOCK_DEPTH - 0.6) * (-sin(CH_DEG / 2)))))), atan2((SOCK_BOT + SOCK_DEPTH + 0.01) * 0 - ((SOCK_BOT + SOCK_DEPTH - 0.6) * 0), (SOCK_BOT + SOCK_DEPTH + 0.01) * (-1 * cos(CH_DEG / 2)) - ((SOCK_BOT + SOCK_DEPTH - 0.6) * (-1 * cos(CH_DEG / 2))))]) {
            cylinder(h = sqrt(((SOCK_BOT + SOCK_DEPTH + 0.01) * (-1 * cos(CH_DEG / 2)) - ((SOCK_BOT + SOCK_DEPTH - 0.6) * (-1 * cos(CH_DEG / 2)))) * ((SOCK_BOT + SOCK_DEPTH + 0.01) * (-1 * cos(CH_DEG / 2)) - ((SOCK_BOT + SOCK_DEPTH - 0.6) * (-1 * cos(CH_DEG / 2)))) + ((SOCK_BOT + SOCK_DEPTH + 0.01) * 0 - ((SOCK_BOT + SOCK_DEPTH - 0.6) * 0)) * ((SOCK_BOT + SOCK_DEPTH + 0.01) * 0 - ((SOCK_BOT + SOCK_DEPTH - 0.6) * 0)) + ((SOCK_BOT + SOCK_DEPTH + 0.01) * (-sin(CH_DEG / 2)) - ((SOCK_BOT + SOCK_DEPTH - 0.6) * (-sin(CH_DEG / 2)))) * ((SOCK_BOT + SOCK_DEPTH + 0.01) * (-sin(CH_DEG / 2)) - ((SOCK_BOT + SOCK_DEPTH - 0.6) * (-sin(CH_DEG / 2))))), r1 = SOCK_D / 2, r2 = SOCK_D / 2 + 0.6, center = false, $fn = 48);
        }
    }
    translate([-4, -8.5, -2]) {
        rotate([0, 90, 0]) {
            cylinder(h = 8, r = M3_CLEAR / 2, center = false, $fn = 20);
        }
    }
    translate([-3.01, -8.5, -2]) {
        rotate([0, 90, 0]) {
            cylinder(h = 2.5, r = (M3_NUT_AF + 0.2) / 1.732051, center = false, $fn = 6);
        }
    }
    translate([-4, 8.5, -2]) {
        rotate([0, 90, 0]) {
            cylinder(h = 8, r = M3_CLEAR / 2, center = false, $fn = 20);
        }
    }
    translate([-3.01, 8.5, -2]) {
        rotate([0, 90, 0]) {
            cylinder(h = 2.5, r = (M3_NUT_AF + 0.2) / 1.732051, center = false, $fn = 6);
        }
    }
    translate([-6.5, 12.5, -6.1]) {
        cube([3, 5, 4.2], center = false);
    }
}
