// H09L_shoulder_node  (qty 1; frame: node; MJF PA12; print service OK)
// GENERATED by gen_halo_stl.py from halo_parts.py. Change numbers in halo_params.scad.
// Every dimension below is an expression of the names in halo_params.scad.
include <../halo_params.scad>

difference() {
    union() {
        translate([0, 0, 0]) {
            rotate([0, acos(((SOCK_BOT + SOCK_DEPTH) * (-sin(CH_DEG / 2)) - 0) / sqrt(((SOCK_BOT + SOCK_DEPTH) * (-cos(CH_DEG / 2)) - 0) * ((SOCK_BOT + SOCK_DEPTH) * (-cos(CH_DEG / 2)) - 0) + ((SOCK_BOT + SOCK_DEPTH) * 0 - 0) * ((SOCK_BOT + SOCK_DEPTH) * 0 - 0) + ((SOCK_BOT + SOCK_DEPTH) * (-sin(CH_DEG / 2)) - 0) * ((SOCK_BOT + SOCK_DEPTH) * (-sin(CH_DEG / 2)) - 0))), atan2((SOCK_BOT + SOCK_DEPTH) * 0 - 0, (SOCK_BOT + SOCK_DEPTH) * (-cos(CH_DEG / 2)) - 0)]) {
                cylinder(h = sqrt(((SOCK_BOT + SOCK_DEPTH) * (-cos(CH_DEG / 2)) - 0) * ((SOCK_BOT + SOCK_DEPTH) * (-cos(CH_DEG / 2)) - 0) + ((SOCK_BOT + SOCK_DEPTH) * 0 - 0) * ((SOCK_BOT + SOCK_DEPTH) * 0 - 0) + ((SOCK_BOT + SOCK_DEPTH) * (-sin(CH_DEG / 2)) - 0) * ((SOCK_BOT + SOCK_DEPTH) * (-sin(CH_DEG / 2)) - 0)), r = SOCK_D / 2 + SOCK_WALL, center = false, $fn = 48);
            }
        }
        translate([0, 0, 0]) {
            rotate([0, acos(((SOCK_BOT + SOCK_DEPTH) * SHL_Z - 0) / sqrt(((SOCK_BOT + SOCK_DEPTH) * SHL_X - 0) * ((SOCK_BOT + SOCK_DEPTH) * SHL_X - 0) + ((SOCK_BOT + SOCK_DEPTH) * 0 - 0) * ((SOCK_BOT + SOCK_DEPTH) * 0 - 0) + ((SOCK_BOT + SOCK_DEPTH) * SHL_Z - 0) * ((SOCK_BOT + SOCK_DEPTH) * SHL_Z - 0))), atan2((SOCK_BOT + SOCK_DEPTH) * 0 - 0, (SOCK_BOT + SOCK_DEPTH) * SHL_X - 0)]) {
                cylinder(h = sqrt(((SOCK_BOT + SOCK_DEPTH) * SHL_X - 0) * ((SOCK_BOT + SOCK_DEPTH) * SHL_X - 0) + ((SOCK_BOT + SOCK_DEPTH) * 0 - 0) * ((SOCK_BOT + SOCK_DEPTH) * 0 - 0) + ((SOCK_BOT + SOCK_DEPTH) * SHL_Z - 0) * ((SOCK_BOT + SOCK_DEPTH) * SHL_Z - 0)), r = SOCK_D / 2 + SOCK_WALL, center = false, $fn = 48);
            }
        }
        sphere(r = SOCK_D / 2 + SOCK_WALL, $fn = 32);
        union() {
            translate([-3, 5, -6]) {
                cube([6, 7, 4], center = false);
            }
            translate([-3, 11.9, -6]) {
                cube([6, 7.1, 4], center = false);
            }
        }
    }
    translate([SOCK_BOT * (-cos(CH_DEG / 2)), SOCK_BOT * 0, SOCK_BOT * (-sin(CH_DEG / 2))]) {
        rotate([0, acos(((SOCK_BOT + SOCK_DEPTH + 0.1) * (-sin(CH_DEG / 2)) - (SOCK_BOT * (-sin(CH_DEG / 2)))) / sqrt(((SOCK_BOT + SOCK_DEPTH + 0.1) * (-cos(CH_DEG / 2)) - (SOCK_BOT * (-cos(CH_DEG / 2)))) * ((SOCK_BOT + SOCK_DEPTH + 0.1) * (-cos(CH_DEG / 2)) - (SOCK_BOT * (-cos(CH_DEG / 2)))) + ((SOCK_BOT + SOCK_DEPTH + 0.1) * 0 - (SOCK_BOT * 0)) * ((SOCK_BOT + SOCK_DEPTH + 0.1) * 0 - (SOCK_BOT * 0)) + ((SOCK_BOT + SOCK_DEPTH + 0.1) * (-sin(CH_DEG / 2)) - (SOCK_BOT * (-sin(CH_DEG / 2)))) * ((SOCK_BOT + SOCK_DEPTH + 0.1) * (-sin(CH_DEG / 2)) - (SOCK_BOT * (-sin(CH_DEG / 2)))))), atan2((SOCK_BOT + SOCK_DEPTH + 0.1) * 0 - (SOCK_BOT * 0), (SOCK_BOT + SOCK_DEPTH + 0.1) * (-cos(CH_DEG / 2)) - (SOCK_BOT * (-cos(CH_DEG / 2))))]) {
            cylinder(h = sqrt(((SOCK_BOT + SOCK_DEPTH + 0.1) * (-cos(CH_DEG / 2)) - (SOCK_BOT * (-cos(CH_DEG / 2)))) * ((SOCK_BOT + SOCK_DEPTH + 0.1) * (-cos(CH_DEG / 2)) - (SOCK_BOT * (-cos(CH_DEG / 2)))) + ((SOCK_BOT + SOCK_DEPTH + 0.1) * 0 - (SOCK_BOT * 0)) * ((SOCK_BOT + SOCK_DEPTH + 0.1) * 0 - (SOCK_BOT * 0)) + ((SOCK_BOT + SOCK_DEPTH + 0.1) * (-sin(CH_DEG / 2)) - (SOCK_BOT * (-sin(CH_DEG / 2)))) * ((SOCK_BOT + SOCK_DEPTH + 0.1) * (-sin(CH_DEG / 2)) - (SOCK_BOT * (-sin(CH_DEG / 2))))), r = SOCK_D / 2, center = false, $fn = 48);
        }
    }
    translate([(SOCK_BOT + SOCK_DEPTH - 0.6) * (-cos(CH_DEG / 2)), (SOCK_BOT + SOCK_DEPTH - 0.6) * 0, (SOCK_BOT + SOCK_DEPTH - 0.6) * (-sin(CH_DEG / 2))]) {
        rotate([0, acos(((SOCK_BOT + SOCK_DEPTH + 0.01) * (-sin(CH_DEG / 2)) - ((SOCK_BOT + SOCK_DEPTH - 0.6) * (-sin(CH_DEG / 2)))) / sqrt(((SOCK_BOT + SOCK_DEPTH + 0.01) * (-cos(CH_DEG / 2)) - ((SOCK_BOT + SOCK_DEPTH - 0.6) * (-cos(CH_DEG / 2)))) * ((SOCK_BOT + SOCK_DEPTH + 0.01) * (-cos(CH_DEG / 2)) - ((SOCK_BOT + SOCK_DEPTH - 0.6) * (-cos(CH_DEG / 2)))) + ((SOCK_BOT + SOCK_DEPTH + 0.01) * 0 - ((SOCK_BOT + SOCK_DEPTH - 0.6) * 0)) * ((SOCK_BOT + SOCK_DEPTH + 0.01) * 0 - ((SOCK_BOT + SOCK_DEPTH - 0.6) * 0)) + ((SOCK_BOT + SOCK_DEPTH + 0.01) * (-sin(CH_DEG / 2)) - ((SOCK_BOT + SOCK_DEPTH - 0.6) * (-sin(CH_DEG / 2)))) * ((SOCK_BOT + SOCK_DEPTH + 0.01) * (-sin(CH_DEG / 2)) - ((SOCK_BOT + SOCK_DEPTH - 0.6) * (-sin(CH_DEG / 2)))))), atan2((SOCK_BOT + SOCK_DEPTH + 0.01) * 0 - ((SOCK_BOT + SOCK_DEPTH - 0.6) * 0), (SOCK_BOT + SOCK_DEPTH + 0.01) * (-cos(CH_DEG / 2)) - ((SOCK_BOT + SOCK_DEPTH - 0.6) * (-cos(CH_DEG / 2))))]) {
            cylinder(h = sqrt(((SOCK_BOT + SOCK_DEPTH + 0.01) * (-cos(CH_DEG / 2)) - ((SOCK_BOT + SOCK_DEPTH - 0.6) * (-cos(CH_DEG / 2)))) * ((SOCK_BOT + SOCK_DEPTH + 0.01) * (-cos(CH_DEG / 2)) - ((SOCK_BOT + SOCK_DEPTH - 0.6) * (-cos(CH_DEG / 2)))) + ((SOCK_BOT + SOCK_DEPTH + 0.01) * 0 - ((SOCK_BOT + SOCK_DEPTH - 0.6) * 0)) * ((SOCK_BOT + SOCK_DEPTH + 0.01) * 0 - ((SOCK_BOT + SOCK_DEPTH - 0.6) * 0)) + ((SOCK_BOT + SOCK_DEPTH + 0.01) * (-sin(CH_DEG / 2)) - ((SOCK_BOT + SOCK_DEPTH - 0.6) * (-sin(CH_DEG / 2)))) * ((SOCK_BOT + SOCK_DEPTH + 0.01) * (-sin(CH_DEG / 2)) - ((SOCK_BOT + SOCK_DEPTH - 0.6) * (-sin(CH_DEG / 2))))), r1 = SOCK_D / 2, r2 = SOCK_D / 2 + 0.6, center = false, $fn = 48);
        }
    }
    translate([SOCK_BOT * SHL_X, SOCK_BOT * 0, SOCK_BOT * SHL_Z]) {
        rotate([0, acos(((SOCK_BOT + SOCK_DEPTH + 0.1) * SHL_Z - (SOCK_BOT * SHL_Z)) / sqrt(((SOCK_BOT + SOCK_DEPTH + 0.1) * SHL_X - (SOCK_BOT * SHL_X)) * ((SOCK_BOT + SOCK_DEPTH + 0.1) * SHL_X - (SOCK_BOT * SHL_X)) + ((SOCK_BOT + SOCK_DEPTH + 0.1) * 0 - (SOCK_BOT * 0)) * ((SOCK_BOT + SOCK_DEPTH + 0.1) * 0 - (SOCK_BOT * 0)) + ((SOCK_BOT + SOCK_DEPTH + 0.1) * SHL_Z - (SOCK_BOT * SHL_Z)) * ((SOCK_BOT + SOCK_DEPTH + 0.1) * SHL_Z - (SOCK_BOT * SHL_Z)))), atan2((SOCK_BOT + SOCK_DEPTH + 0.1) * 0 - (SOCK_BOT * 0), (SOCK_BOT + SOCK_DEPTH + 0.1) * SHL_X - (SOCK_BOT * SHL_X))]) {
            cylinder(h = sqrt(((SOCK_BOT + SOCK_DEPTH + 0.1) * SHL_X - (SOCK_BOT * SHL_X)) * ((SOCK_BOT + SOCK_DEPTH + 0.1) * SHL_X - (SOCK_BOT * SHL_X)) + ((SOCK_BOT + SOCK_DEPTH + 0.1) * 0 - (SOCK_BOT * 0)) * ((SOCK_BOT + SOCK_DEPTH + 0.1) * 0 - (SOCK_BOT * 0)) + ((SOCK_BOT + SOCK_DEPTH + 0.1) * SHL_Z - (SOCK_BOT * SHL_Z)) * ((SOCK_BOT + SOCK_DEPTH + 0.1) * SHL_Z - (SOCK_BOT * SHL_Z))), r = SOCK_D / 2, center = false, $fn = 48);
        }
    }
    translate([(SOCK_BOT + SOCK_DEPTH - 0.6) * SHL_X, (SOCK_BOT + SOCK_DEPTH - 0.6) * 0, (SOCK_BOT + SOCK_DEPTH - 0.6) * SHL_Z]) {
        rotate([0, acos(((SOCK_BOT + SOCK_DEPTH + 0.01) * SHL_Z - ((SOCK_BOT + SOCK_DEPTH - 0.6) * SHL_Z)) / sqrt(((SOCK_BOT + SOCK_DEPTH + 0.01) * SHL_X - ((SOCK_BOT + SOCK_DEPTH - 0.6) * SHL_X)) * ((SOCK_BOT + SOCK_DEPTH + 0.01) * SHL_X - ((SOCK_BOT + SOCK_DEPTH - 0.6) * SHL_X)) + ((SOCK_BOT + SOCK_DEPTH + 0.01) * 0 - ((SOCK_BOT + SOCK_DEPTH - 0.6) * 0)) * ((SOCK_BOT + SOCK_DEPTH + 0.01) * 0 - ((SOCK_BOT + SOCK_DEPTH - 0.6) * 0)) + ((SOCK_BOT + SOCK_DEPTH + 0.01) * SHL_Z - ((SOCK_BOT + SOCK_DEPTH - 0.6) * SHL_Z)) * ((SOCK_BOT + SOCK_DEPTH + 0.01) * SHL_Z - ((SOCK_BOT + SOCK_DEPTH - 0.6) * SHL_Z)))), atan2((SOCK_BOT + SOCK_DEPTH + 0.01) * 0 - ((SOCK_BOT + SOCK_DEPTH - 0.6) * 0), (SOCK_BOT + SOCK_DEPTH + 0.01) * SHL_X - ((SOCK_BOT + SOCK_DEPTH - 0.6) * SHL_X))]) {
            cylinder(h = sqrt(((SOCK_BOT + SOCK_DEPTH + 0.01) * SHL_X - ((SOCK_BOT + SOCK_DEPTH - 0.6) * SHL_X)) * ((SOCK_BOT + SOCK_DEPTH + 0.01) * SHL_X - ((SOCK_BOT + SOCK_DEPTH - 0.6) * SHL_X)) + ((SOCK_BOT + SOCK_DEPTH + 0.01) * 0 - ((SOCK_BOT + SOCK_DEPTH - 0.6) * 0)) * ((SOCK_BOT + SOCK_DEPTH + 0.01) * 0 - ((SOCK_BOT + SOCK_DEPTH - 0.6) * 0)) + ((SOCK_BOT + SOCK_DEPTH + 0.01) * SHL_Z - ((SOCK_BOT + SOCK_DEPTH - 0.6) * SHL_Z)) * ((SOCK_BOT + SOCK_DEPTH + 0.01) * SHL_Z - ((SOCK_BOT + SOCK_DEPTH - 0.6) * SHL_Z))), r1 = SOCK_D / 2, r2 = SOCK_D / 2 + 0.6, center = false, $fn = 48);
        }
    }
    translate([-1.5, 13, -6.1]) {
        cube([3, 5, 4.2], center = false);
    }
}
