// H10_carriage  (qty 1; frame: carriage; MJF PA12; needs iteration (roller fit), home printer helps)
// GENERATED by gen_halo_stl.py from halo_parts.py. Change numbers in halo_params.scad.
// Every dimension below is an expression of the names in halo_params.scad.
include <../halo_params.scad>

difference() {
    union() {
        translate([-(CAR_L / 2), STRIP_W / 2 + GUIDE_GAP, -9]) {
            cube([CAR_L / 2 - (-(CAR_L / 2)), STRIP_W / 2 + GUIDE_GAP + CHEEK_T - (STRIP_W / 2 + GUIDE_GAP), 20], center = false);
        }
        translate([-(CAR_L / 2), -(STRIP_W / 2 + GUIDE_GAP) - LIP_T, 8]) {
            cube([CAR_L / 2 - (-(CAR_L / 2)), STRIP_W / 2 + GUIDE_GAP + CHEEK_T - (-(STRIP_W / 2 + GUIDE_GAP) - LIP_T), 3], center = false);
        }
        translate([-(CAR_L / 2), -(STRIP_W / 2 + GUIDE_GAP) - LIP_T, -1.5]) {
            cube([CAR_L / 2 - (-(CAR_L / 2)), -(STRIP_W / 2 + GUIDE_GAP) - (-(STRIP_W / 2 + GUIDE_GAP) - LIP_T), 12.5], center = false);
        }
        translate([-1 * ((R_SI + STRIP_T + ROLL_D / 2) * sin((ROLL_S / (R_SI + STRIP_T)) * 57.29578)), STRIP_W / 2 + GUIDE_GAP, (R_SI + STRIP_T + ROLL_D / 2) * cos((ROLL_S / (R_SI + STRIP_T)) * 57.29578) - R_SI]) {
            rotate([90, 0, 0]) {
                cylinder(h = STRIP_W / 2 + GUIDE_GAP - (ROLL_W / 2) - 0.2, r = 2.5, center = false, $fn = 24);
            }
        }
        translate([-1 * ((R_SI + STRIP_T + ROLL_D / 2) * sin((ROLL_S / (R_SI + STRIP_T)) * 57.29578)), -(STRIP_W / 2 + GUIDE_GAP) + STRIP_W / 2 + GUIDE_GAP - (ROLL_W / 2) - 0.2, (R_SI + STRIP_T + ROLL_D / 2) * cos((ROLL_S / (R_SI + STRIP_T)) * 57.29578) - R_SI]) {
            rotate([90, 0, 0]) {
                cylinder(h = STRIP_W / 2 + GUIDE_GAP - (ROLL_W / 2) - 0.2, r = 2.5, center = false, $fn = 24);
            }
        }
        translate([-1 * ((R_SI - (ROLL_D / 2)) * sin((ROLL_S / R_SI) * 57.29578)), STRIP_W / 2 + GUIDE_GAP, (R_SI - (ROLL_D / 2)) * cos((ROLL_S / R_SI) * 57.29578) - R_SI]) {
            rotate([90, 0, 0]) {
                cylinder(h = 0.85, r = 2.5, center = false, $fn = 24);
            }
        }
        translate([1 * ((R_SI + STRIP_T + ROLL_D / 2) * sin((ROLL_S / (R_SI + STRIP_T)) * 57.29578)), STRIP_W / 2 + GUIDE_GAP, (R_SI + STRIP_T + ROLL_D / 2) * cos((ROLL_S / (R_SI + STRIP_T)) * 57.29578) - R_SI]) {
            rotate([90, 0, 0]) {
                cylinder(h = STRIP_W / 2 + GUIDE_GAP - (ROLL_W / 2) - 0.2, r = 2.5, center = false, $fn = 24);
            }
        }
        translate([1 * ((R_SI + STRIP_T + ROLL_D / 2) * sin((ROLL_S / (R_SI + STRIP_T)) * 57.29578)), -(STRIP_W / 2 + GUIDE_GAP) + STRIP_W / 2 + GUIDE_GAP - (ROLL_W / 2) - 0.2, (R_SI + STRIP_T + ROLL_D / 2) * cos((ROLL_S / (R_SI + STRIP_T)) * 57.29578) - R_SI]) {
            rotate([90, 0, 0]) {
                cylinder(h = STRIP_W / 2 + GUIDE_GAP - (ROLL_W / 2) - 0.2, r = 2.5, center = false, $fn = 24);
            }
        }
        translate([1 * ((R_SI - (ROLL_D / 2)) * sin((ROLL_S / R_SI) * 57.29578)), STRIP_W / 2 + GUIDE_GAP, (R_SI - (ROLL_D / 2)) * cos((ROLL_S / R_SI) * 57.29578) - R_SI]) {
            rotate([90, 0, 0]) {
                cylinder(h = 0.85, r = 2.5, center = false, $fn = 24);
            }
        }
        translate([DET_X, STRIP_W / 2 + GUIDE_GAP + CHEEK_T - 0.01, 0.5]) {
            rotate([-90, 0, 0]) {
                cylinder(h = 5, r = 4, center = false, $fn = 32);
            }
        }
        translate([0, 0, 10.99]) {
            cylinder(h = 6, r = 4, center = false, $fn = 32);
        }
        translate([0, 0, 0]) {
            translate([0, 0, -R_SI]) {
                rotate([-DELTA, 0, 0]) {
                    translate([0, 0, RHO_PLATE0]) {
                        linear_extrude(height = AIR_PLATE_T, center = false) polygon([[10, -16], [11.14805, -15.771639], [12.12132, -15.12132], [12.771639, -14.14805], [13, -13], [13, 10], [12.771639, 11.14805], [12.12132, 12.12132], [11.14805, 12.771639], [10, 13], [-10, 13], [-11.14805, 12.771639], [-12.12132, 12.12132], [-12.771639, 11.14805], [-13, 10], [-13, -13], [-12.771639, -14.14805], [-12.12132, -15.12132], [-11.14805, -15.771639], [-10, -16]]);
                    }
                }
            }
        }
        translate([0, 0, -R_SI]) {
            rotate([-DELTA, 0, 0]) {
                translate([0, 0, RHO_PLATE1 + 18]) {
                    cylinder(h = RHO_PLATE1 + 26 - (RHO_PLATE1 + 18), r = 13, center = false, $fn = 48);
                }
            }
        }
        translate([0, 0, -R_SI]) {
            rotate([-DELTA, 0, 0]) {
                translate([-GUIDE_R, 0, RHO_PLATE1 + 18]) {
                    cylinder(h = RHO_PLATE1 + 26 - (RHO_PLATE1 + 18), r = 3.5, center = false, $fn = 24);
                }
            }
        }
        translate([0, 0, -R_SI]) {
            rotate([-DELTA, 0, 0]) {
                union() {
                    translate([0, 0, RHO_PLATE1 + 18]) {
                        translate([10.5, CF_W / 2 + 0.6, 0]) {
                            cube([CF_X + 1 - 10.5, CF_W / 2 + 2.1 - (CF_W / 2 + 0.6), RHO_PLATE1 + 26 - (RHO_PLATE1 + 18) + 4 - 0], center = false);
                        }
                    }
                    translate([0, 0, RHO_PLATE1 + 18]) {
                        translate([10.5, (-CF_W) / 2 - 2.1, 0]) {
                            cube([CF_X + 1 - 10.5, (-CF_W) / 2 - 0.6 - ((-CF_W) / 2 - 2.1), RHO_PLATE1 + 26 - (RHO_PLATE1 + 18) + 4 - 0], center = false);
                        }
                    }
                }
            }
        }
        translate([-5, 8, 8]) {
            cube([10, 5.5, 9], center = false);
        }
        translate([-15, -(STRIP_W / 2 + GUIDE_GAP) - LIP_T - 6, 8]) {
            cube([11, -(STRIP_W / 2 + GUIDE_GAP) - LIP_T + 0.01 - (-(STRIP_W / 2 + GUIDE_GAP) - LIP_T - 6), 3], center = false);
        }
    }
    translate([-1 * ((R_SI + STRIP_T + ROLL_D / 2) * sin((ROLL_S / (R_SI + STRIP_T)) * 57.29578)), STRIP_W / 2 + GUIDE_GAP + CHEEK_T + 1, (R_SI + STRIP_T + ROLL_D / 2) * cos((ROLL_S / (R_SI + STRIP_T)) * 57.29578) - R_SI]) {
        rotate([90, 0, 0]) {
            cylinder(h = STRIP_W / 2 + GUIDE_GAP + CHEEK_T - (-(STRIP_W / 2 + GUIDE_GAP) - LIP_T) + 2, r = 1.45, center = false, $fn = 20);
        }
    }
    translate([-1 * ((R_SI - (ROLL_D / 2)) * sin((ROLL_S / R_SI) * 57.29578)), STRIP_W / 2 + GUIDE_GAP + CHEEK_T + 1, (R_SI - (ROLL_D / 2)) * cos((ROLL_S / R_SI) * 57.29578) - R_SI]) {
        rotate([90, 0, 0]) {
            cylinder(h = STRIP_W / 2 + GUIDE_GAP + CHEEK_T - 3, r = 1.45, center = false, $fn = 20);
        }
    }
    translate([1 * ((R_SI + STRIP_T + ROLL_D / 2) * sin((ROLL_S / (R_SI + STRIP_T)) * 57.29578)), STRIP_W / 2 + GUIDE_GAP + CHEEK_T + 1, (R_SI + STRIP_T + ROLL_D / 2) * cos((ROLL_S / (R_SI + STRIP_T)) * 57.29578) - R_SI]) {
        rotate([90, 0, 0]) {
            cylinder(h = STRIP_W / 2 + GUIDE_GAP + CHEEK_T - (-(STRIP_W / 2 + GUIDE_GAP) - LIP_T) + 2, r = 1.45, center = false, $fn = 20);
        }
    }
    translate([1 * ((R_SI - (ROLL_D / 2)) * sin((ROLL_S / R_SI) * 57.29578)), STRIP_W / 2 + GUIDE_GAP + CHEEK_T + 1, (R_SI - (ROLL_D / 2)) * cos((ROLL_S / R_SI) * 57.29578) - R_SI]) {
        rotate([90, 0, 0]) {
            cylinder(h = STRIP_W / 2 + GUIDE_GAP + CHEEK_T - 3, r = 1.45, center = false, $fn = 20);
        }
    }
    translate([DET_X, STRIP_W / 2 + GUIDE_GAP + CHEEK_T + 5 - M4_INS_L, 0.5]) {
        rotate([-90, 0, 0]) {
            cylinder(h = M4_INS_L + 0.1, r = M4_INS_D / 2, center = false, $fn = 24);
        }
    }
    translate([DET_X, STRIP_W / 2 + GUIDE_GAP - 0.1, 0.5]) {
        rotate([-90, 0, 0]) {
            cylinder(h = STRIP_W / 2 + GUIDE_GAP + CHEEK_T + 5, r = 2.1, center = false, $fn = 24);
        }
    }
    translate([-5.2, -1.7, 1.2]) {
        cube([10.4, 3.4, 11.8], center = false);
    }
    translate([0, 0, 17 - M3_INS_L]) {
        cylinder(h = M3_INS_L + 0.1, r = M3_INS_D / 2, center = false, $fn = 20);
    }
    translate([0, 0, 10]) {
        cylinder(h = 8, r = 1.7, center = false, $fn = 20);
    }
    translate([0, 0, -R_SI]) {
        rotate([-DELTA, 0, 0]) {
            translate([0, 0, RHO_PLATE0 - 1]) {
                cylinder(h = AIR_PLATE_T + 2, r = AIR_NOSE_D / 2 + 0.2, center = false, $fn = 40);
            }
        }
    }
    translate([0, 0, -R_SI]) {
        rotate([-DELTA, 0, 0]) {
            translate([0, 0, RHO_PLATE1 + 18 - 1]) {
                cylinder(h = RHO_PLATE1 + 26 - (RHO_PLATE1 + 18) + 2, r = AIR_OD / 2 + 0.4, center = false, $fn = 48);
            }
        }
    }
    translate([0, 0, -R_SI]) {
        rotate([-DELTA, 0, 0]) {
            translate([-GUIDE_R, 0, RHO_PLATE1 + 18 - 1]) {
                cylinder(h = RHO_PLATE1 + 26 - (RHO_PLATE1 + 18) + 2, r = GUIDE_D / 2 + 0.15, center = false, $fn = 20);
            }
        }
    }
    translate([0, 0, -R_SI]) {
        rotate([-DELTA, 0, 0]) {
            translate([CF_X - (CF_SPOOL_D / 2) - 0.3, 0, RHO_PLATE1 + 26 - 1]) {
                rotate([90, 0, 0]) {
                    cylinder(h = 20, r = 1.5, center = true, $fn = 20);
                }
            }
        }
    }
    translate([-12.5, -(STRIP_W / 2 + GUIDE_GAP) - LIP_T - 4.5, 7.9]) {
        cube([6, -(STRIP_W / 2 + GUIDE_GAP) - LIP_T - 2.5 - (-(STRIP_W / 2 + GUIDE_GAP) - LIP_T - 4.5), 3.2], center = false);
    }
}
