// H10b_spool  (qty 1; frame: local; MJF PA12 or PETG)
// GENERATED by gen_halo_stl.py from halo_parts.py. Change numbers in halo_params.scad.
// Every dimension below is an expression of the names in halo_params.scad.
include <../halo_params.scad>

difference() {
    cylinder(h = CF_W + 0.4, r = CF_SPOOL_D / 2 - 0.2, center = false, $fn = 40);
    translate([0, 0, -1]) {
        cylinder(h = CF_W + 3, r = 1.65, center = false, $fn = 20);
    }
}
