// H11_beta_stop  (qty 2; frame: local; MJF PA12; print service OK)
// GENERATED by gen_halo_stl.py from halo_parts.py. Change numbers in halo_params.scad.
// Every dimension below is an expression of the names in halo_params.scad.
include <../halo_params.scad>

difference() {
    union() {
        rotate([0, 90, 0]) {
            cylinder(h = 10, r = 7, center = false, $fn = 40);
        }
        translate([0, -6, 3]) {
            cube([10, 12, 6.5], center = false);
        }
        translate([0, 3, 3]) {
            cube([4, 7, R_SI + 12 - (R_BAIL * cos(CH_DEG / 2)) - 3], center = false);
        }
    }
    translate([-1, 0, 0]) {
        rotate([0, 90, 0]) {
            cylinder(h = 12, r = 4.05, center = false, $fn = 40);
        }
    }
    translate([-1, -0.75, 0]) {
        cube([12, 1.5, 9.6], center = false);
    }
    translate([5, -7, 6.5]) {
        rotate([-90, 0, 0]) {
            cylinder(h = 14, r = M3_CLEAR / 2, center = false, $fn = 20);
        }
    }
    translate([5, -6.01, 6.5]) {
        rotate([-90, 0, 0]) {
            cylinder(h = 2.5, r = (M3_NUT_AF + 0.2) / 1.732051, center = false, $fn = 6);
        }
    }
}
