// H12_spider  (qty 1; frame: spider; MJF PA12; print service OK)
// GENERATED by gen_halo_stl.py from halo_parts.py. Change numbers in halo_params.scad.
// Every dimension below is an expression of the names in halo_params.scad.
include <../halo_params.scad>

difference() {
    union() {
        hull() {
            translate([0, 0, -SPIDER_ARM_T]) {
                cylinder(h = SPIDER_ARM_T, r = 3, center = false, $fn = 48);
            }
            translate([MAG_R * cos(SPIDER_ANG0), MAG_R * sin(SPIDER_ANG0), -SPIDER_ARM_T]) {
                cylinder(h = SPIDER_ARM_T, r = 4.3, center = false, $fn = 48);
            }
        }
        hull() {
            translate([MAG_R * cos(SPIDER_ANG0), MAG_R * sin(SPIDER_ANG0), -SPIDER_ARM_T]) {
                cylinder(h = SPIDER_ARM_T, r = 4.3, center = false, $fn = 48);
            }
            translate([SPIDER_R * cos(SPIDER_ANG0), SPIDER_R * sin(SPIDER_ANG0), -SPIDER_ARM_T]) {
                cylinder(h = SPIDER_ARM_T, r = 3.6, center = false, $fn = 48);
            }
        }
        hull() {
            translate([0, 0, -SPIDER_ARM_T]) {
                cylinder(h = SPIDER_ARM_T, r = 3, center = false, $fn = 48);
            }
            translate([MAG_R * cos(SPIDER_ANG0 + 120), MAG_R * sin(SPIDER_ANG0 + 120), -SPIDER_ARM_T]) {
                cylinder(h = SPIDER_ARM_T, r = 4.3, center = false, $fn = 48);
            }
        }
        hull() {
            translate([MAG_R * cos(SPIDER_ANG0 + 120), MAG_R * sin(SPIDER_ANG0 + 120), -SPIDER_ARM_T]) {
                cylinder(h = SPIDER_ARM_T, r = 4.3, center = false, $fn = 48);
            }
            translate([SPIDER_R * cos(SPIDER_ANG0 + 120), SPIDER_R * sin(SPIDER_ANG0 + 120), -SPIDER_ARM_T]) {
                cylinder(h = SPIDER_ARM_T, r = 3.6, center = false, $fn = 48);
            }
        }
        hull() {
            translate([0, 0, -SPIDER_ARM_T]) {
                cylinder(h = SPIDER_ARM_T, r = 3, center = false, $fn = 48);
            }
            translate([MAG_R * cos(SPIDER_ANG0 + 240), MAG_R * sin(SPIDER_ANG0 + 240), -SPIDER_ARM_T]) {
                cylinder(h = SPIDER_ARM_T, r = 4.3, center = false, $fn = 48);
            }
        }
        hull() {
            translate([MAG_R * cos(SPIDER_ANG0 + 240), MAG_R * sin(SPIDER_ANG0 + 240), -SPIDER_ARM_T]) {
                cylinder(h = SPIDER_ARM_T, r = 4.3, center = false, $fn = 48);
            }
            translate([SPIDER_R * cos(SPIDER_ANG0 + 240), SPIDER_R * sin(SPIDER_ANG0 + 240), -SPIDER_ARM_T]) {
                cylinder(h = SPIDER_ARM_T, r = 3.6, center = false, $fn = 48);
            }
        }
        translate([0, 0, -SPIDER_HUB_T]) {
            cylinder(h = SPIDER_HUB_T, r = SPIDER_HUB_D / 2, center = false, $fn = 48);
        }
        translate([-GUIDE_R, 0, -SPIDER_ARM_T]) {
            cylinder(h = SPIDER_ARM_T + 6, r = 3.5, center = false, $fn = 32);
        }
        hull() {
            translate([0, 0, -SPIDER_ARM_T]) {
                cylinder(h = SPIDER_ARM_T, r = 3, center = false, $fn = 48);
            }
            translate([-GUIDE_R, 0, -SPIDER_ARM_T]) {
                cylinder(h = SPIDER_ARM_T, r = 3.5, center = false, $fn = 48);
            }
        }
        hull() {
            translate([0, 0, -SPIDER_ARM_T]) {
                cylinder(h = SPIDER_ARM_T, r = 3, center = false, $fn = 48);
            }
            translate([CF_X, 0, -SPIDER_ARM_T]) {
                cylinder(h = SPIDER_ARM_T, r = 4, center = false, $fn = 48);
            }
        }
    }
    translate([0, 0, -SPIDER_HUB_T - 1]) {
        cylinder(h = SPIDER_HUB_T + 2, r = ROD_HOLE / 2, center = false, $fn = 24);
    }
    translate([0, 0, -SPIDER_HUB_T - 0.01]) {
        cylinder(h = ROD_NUT_T + 0.01, r = ROD_NUT_AF / 1.732051, center = false, $fn = 6);
    }
    translate([-GUIDE_R, 0, -2]) {
        cylinder(h = 8.1, r = GUIDE_D / 2 + 0.03, center = false, $fn = 20);
    }
    translate([CF_X, 0, -SPIDER_ARM_T - 1]) {
        cylinder(h = SPIDER_ARM_T + 2, r = 1.1, center = false, $fn = 16);
    }
    translate([SPIDER_R * cos(SPIDER_ANG0), SPIDER_R * sin(SPIDER_ANG0), -SPIDER_ARM_T - (BALL_D / 2) + 2.05]) {
        sphere(r = BALL_D / 2 + 0.05, $fn = 24);
    }
    translate([MAG_R * cos(SPIDER_ANG0), MAG_R * sin(SPIDER_ANG0), -SPIDER_ARM_T - 0.01]) {
        cylinder(h = MAG_T + 0.11, r = MAG_D / 2 + 0.05, center = false, $fn = 24);
    }
    translate([SPIDER_R * cos(SPIDER_ANG0 + 120), SPIDER_R * sin(SPIDER_ANG0 + 120), -SPIDER_ARM_T - (BALL_D / 2) + 2.05]) {
        sphere(r = BALL_D / 2 + 0.05, $fn = 24);
    }
    translate([MAG_R * cos(SPIDER_ANG0 + 120), MAG_R * sin(SPIDER_ANG0 + 120), -SPIDER_ARM_T - 0.01]) {
        cylinder(h = MAG_T + 0.11, r = MAG_D / 2 + 0.05, center = false, $fn = 24);
    }
    translate([SPIDER_R * cos(SPIDER_ANG0 + 240), SPIDER_R * sin(SPIDER_ANG0 + 240), -SPIDER_ARM_T - (BALL_D / 2) + 2.05]) {
        sphere(r = BALL_D / 2 + 0.05, $fn = 24);
    }
    translate([MAG_R * cos(SPIDER_ANG0 + 240), MAG_R * sin(SPIDER_ANG0 + 240), -SPIDER_ARM_T - 0.01]) {
        cylinder(h = MAG_T + 0.11, r = MAG_D / 2 + 0.05, center = false, $fn = 24);
    }
}
