// H13_forehead_node  (qty 1; frame: H; MJF PA12; needs one fit iteration (forehead curve))
// GENERATED by gen_halo_stl.py from halo_parts.py. Change numbers in halo_params.scad.
// Every dimension below is an expression of the names in halo_params.scad.
include <../halo_params.scad>

difference() {
    union() {
        translate([X_NC, 0, 0]) {
            rotate([0, 0, -((NODE_HALF / R_NB) * 57.29578)]) {
                rotate_extrude(angle = 2 * ((NODE_HALF / R_NB) * 57.29578), $fn = 72) polygon([[R_NB + 2.6 - 0.9 + 0, BAND_Z_FRONT - 12 + 0.9 + -0.9], [R_NB + 2.6 - 0.9 + 0.45, BAND_Z_FRONT - 12 + 0.9 + -0.779423], [R_NB + 2.6 - 0.9 + 0.779423, BAND_Z_FRONT - 12 + 0.9 + -0.45], [R_NB + 2.6 - 0.9 + 0.9, BAND_Z_FRONT - 12 + 0.9 + 0], [R_NB + 2.6 - 0.9 + 0.9, BAND_Z_FRONT + 12 - 0.9 + 0], [R_NB + 2.6 - 0.9 + 0.779423, BAND_Z_FRONT + 12 - 0.9 + 0.45], [R_NB + 2.6 - 0.9 + 0.45, BAND_Z_FRONT + 12 - 0.9 + 0.779423], [R_NB + 2.6 - 0.9 + 0, BAND_Z_FRONT + 12 - 0.9 + 0.9], [R_NB - 1.8 + 0.9 + 0, BAND_Z_FRONT + 12 - 0.9 + 0.9], [R_NB - 1.8 + 0.9 + -0.45, BAND_Z_FRONT + 12 - 0.9 + 0.779423], [R_NB - 1.8 + 0.9 + -0.779423, BAND_Z_FRONT + 12 - 0.9 + 0.45], [R_NB - 1.8 + 0.9 + -0.9, BAND_Z_FRONT + 12 - 0.9 + 0], [R_NB - 1.8 + 0.9 + -0.9, BAND_Z_FRONT - 12 + 0.9 + 0], [R_NB - 1.8 + 0.9 + -0.779423, BAND_Z_FRONT - 12 + 0.9 + -0.45], [R_NB - 1.8 + 0.9 + -0.45, BAND_Z_FRONT - 12 + 0.9 + -0.779423], [R_NB - 1.8 + 0.9 + 0, BAND_Z_FRONT - 12 + 0.9 + -0.9]]);
            }
        }
        translate([X_NC, 0, 0]) {
            rotate([0, 0, -((14 / R_NB) * 57.29578)]) {
                rotate_extrude(angle = 2 * ((14 / R_NB) * 57.29578), $fn = 72) polygon([[R_NB + 5 - 0.9 + 0, BAND_Z_FRONT - 24 + 0.9 + -0.9], [R_NB + 5 - 0.9 + 0.45, BAND_Z_FRONT - 24 + 0.9 + -0.779423], [R_NB + 5 - 0.9 + 0.779423, BAND_Z_FRONT - 24 + 0.9 + -0.45], [R_NB + 5 - 0.9 + 0.9, BAND_Z_FRONT - 24 + 0.9 + 0], [R_NB + 5 - 0.9 + 0.9, BAND_Z_FRONT - 11 - 0.9 + 0], [R_NB + 5 - 0.9 + 0.779423, BAND_Z_FRONT - 11 - 0.9 + 0.45], [R_NB + 5 - 0.9 + 0.45, BAND_Z_FRONT - 11 - 0.9 + 0.779423], [R_NB + 5 - 0.9 + 0, BAND_Z_FRONT - 11 - 0.9 + 0.9], [R_NB - 1.8 + 0.9 + 0, BAND_Z_FRONT - 11 - 0.9 + 0.9], [R_NB - 1.8 + 0.9 + -0.45, BAND_Z_FRONT - 11 - 0.9 + 0.779423], [R_NB - 1.8 + 0.9 + -0.779423, BAND_Z_FRONT - 11 - 0.9 + 0.45], [R_NB - 1.8 + 0.9 + -0.9, BAND_Z_FRONT - 11 - 0.9 + 0], [R_NB - 1.8 + 0.9 + -0.9, BAND_Z_FRONT - 24 + 0.9 + 0], [R_NB - 1.8 + 0.9 + -0.779423, BAND_Z_FRONT - 24 + 0.9 + -0.45], [R_NB - 1.8 + 0.9 + -0.45, BAND_Z_FRONT - 24 + 0.9 + -0.779423], [R_NB - 1.8 + 0.9 + 0, BAND_Z_FRONT - 24 + 0.9 + -0.9]]);
            }
        }
        translate([X_NC, 0, 0]) {
            rotate([0, 0, -((17 / R_NB) * 57.29578)]) {
                rotate_extrude(angle = 2 * ((17 / R_NB) * 57.29578), $fn = 72) polygon([[R_NB + 13 - 0.9 + 0, BAND_Z_FRONT + 9.5 + 0.9 + -0.9], [R_NB + 13 - 0.9 + 0.45, BAND_Z_FRONT + 9.5 + 0.9 + -0.779423], [R_NB + 13 - 0.9 + 0.779423, BAND_Z_FRONT + 9.5 + 0.9 + -0.45], [R_NB + 13 - 0.9 + 0.9, BAND_Z_FRONT + 9.5 + 0.9 + 0], [R_NB + 13 - 0.9 + 0.9, BAND_Z_FRONT + 12 - 0.9 + 0], [R_NB + 13 - 0.9 + 0.779423, BAND_Z_FRONT + 12 - 0.9 + 0.45], [R_NB + 13 - 0.9 + 0.45, BAND_Z_FRONT + 12 - 0.9 + 0.779423], [R_NB + 13 - 0.9 + 0, BAND_Z_FRONT + 12 - 0.9 + 0.9], [R_NB + 1.6 + 0.9 + 0, BAND_Z_FRONT + 12 - 0.9 + 0.9], [R_NB + 1.6 + 0.9 + -0.45, BAND_Z_FRONT + 12 - 0.9 + 0.779423], [R_NB + 1.6 + 0.9 + -0.779423, BAND_Z_FRONT + 12 - 0.9 + 0.45], [R_NB + 1.6 + 0.9 + -0.9, BAND_Z_FRONT + 12 - 0.9 + 0], [R_NB + 1.6 + 0.9 + -0.9, BAND_Z_FRONT + 9.5 + 0.9 + 0], [R_NB + 1.6 + 0.9 + -0.779423, BAND_Z_FRONT + 9.5 + 0.9 + -0.45], [R_NB + 1.6 + 0.9 + -0.45, BAND_Z_FRONT + 9.5 + 0.9 + -0.779423], [R_NB + 1.6 + 0.9 + 0, BAND_Z_FRONT + 9.5 + 0.9 + -0.9]]);
            }
        }
        translate([X_NC, 0, 0]) {
            rotate([0, 0, -((17 / R_NB) * 57.29578)]) {
                rotate_extrude(angle = 2 * ((17 / R_NB) * 57.29578), $fn = 72) polygon([[R_NB + 13 - 0.9 + 0, BAND_Z_FRONT + 9.5 + 0.9 + -0.9], [R_NB + 13 - 0.9 + 0.45, BAND_Z_FRONT + 9.5 + 0.9 + -0.779423], [R_NB + 13 - 0.9 + 0.779423, BAND_Z_FRONT + 9.5 + 0.9 + -0.45], [R_NB + 13 - 0.9 + 0.9, BAND_Z_FRONT + 9.5 + 0.9 + 0], [R_NB + 13 - 0.9 + 0.9, BAND_Z_FRONT + 16 - 0.9 + 0], [R_NB + 13 - 0.9 + 0.779423, BAND_Z_FRONT + 16 - 0.9 + 0.45], [R_NB + 13 - 0.9 + 0.45, BAND_Z_FRONT + 16 - 0.9 + 0.779423], [R_NB + 13 - 0.9 + 0, BAND_Z_FRONT + 16 - 0.9 + 0.9], [R_NB + 10.5 + 0.9 + 0, BAND_Z_FRONT + 16 - 0.9 + 0.9], [R_NB + 10.5 + 0.9 + -0.45, BAND_Z_FRONT + 16 - 0.9 + 0.779423], [R_NB + 10.5 + 0.9 + -0.779423, BAND_Z_FRONT + 16 - 0.9 + 0.45], [R_NB + 10.5 + 0.9 + -0.9, BAND_Z_FRONT + 16 - 0.9 + 0], [R_NB + 10.5 + 0.9 + -0.9, BAND_Z_FRONT + 9.5 + 0.9 + 0], [R_NB + 10.5 + 0.9 + -0.779423, BAND_Z_FRONT + 9.5 + 0.9 + -0.45], [R_NB + 10.5 + 0.9 + -0.45, BAND_Z_FRONT + 9.5 + 0.9 + -0.779423], [R_NB + 10.5 + 0.9 + 0, BAND_Z_FRONT + 9.5 + 0.9 + -0.9]]);
            }
        }
    }
    translate([X_NC, 0, 0]) {
        rotate([0, 0, -(((NODE_HALF + 2) / R_NB) * 57.29578)]) {
            rotate_extrude(angle = 2 * (((NODE_HALF + 2) / R_NB) * 57.29578), $fn = 72) polygon([[R_NB, BAND_Z_FRONT - 10.3], [R_NB + 1.4, BAND_Z_FRONT - 10.3], [R_NB + 1.4, BAND_Z_FRONT + 10.3], [R_NB, BAND_Z_FRONT + 10.3]]);
        }
    }
    translate([X_NC + R_NB - 1.81, (-SW_L) / 2, BAND_Z_FRONT - 21.4]) {
        cube([SW_H + 0.01, SW_L, SW_W], center = false);
    }
    translate([X_NC + R_NB + 3, -1.5, BAND_Z_FRONT - 21]) {
        cube([4, 3, 4], center = false);
    }
    translate([X_NC + R_NB - 4, -10.5, BAND_Z_FRONT - 18.5]) {
        rotate([0, 90, 0]) {
            cylinder(h = 12, r = 1.6, center = false, $fn = 20);
        }
    }
    translate([X_NC + R_NB - 4, 10.5, BAND_Z_FRONT - 18.5]) {
        rotate([0, 90, 0]) {
            cylinder(h = 12, r = 1.6, center = false, $fn = 20);
        }
    }
}
