// H14_trigger_plate  (qty 1; frame: H; MJF PA12 or PETG)
// GENERATED by gen_halo_stl.py from halo_parts.py. Change numbers in halo_params.scad.
// Every dimension below is an expression of the names in halo_params.scad.
include <../halo_params.scad>

difference() {
    translate([X_NC, 0, 0]) {
        rotate([0, 0, -((13 / R_NB) * 57.29578)]) {
            rotate_extrude(angle = 2 * ((13 / R_NB) * 57.29578), $fn = 72) polygon([[R_NB - 3.3 - 0.9 + 0, BAND_Z_FRONT - 23 + 0.9 + -0.9], [R_NB - 3.3 - 0.9 + 0.45, BAND_Z_FRONT - 23 + 0.9 + -0.779423], [R_NB - 3.3 - 0.9 + 0.779423, BAND_Z_FRONT - 23 + 0.9 + -0.45], [R_NB - 3.3 - 0.9 + 0.9, BAND_Z_FRONT - 23 + 0.9 + 0], [R_NB - 3.3 - 0.9 + 0.9, BAND_Z_FRONT - 12 - 0.9 + 0], [R_NB - 3.3 - 0.9 + 0.779423, BAND_Z_FRONT - 12 - 0.9 + 0.45], [R_NB - 3.3 - 0.9 + 0.45, BAND_Z_FRONT - 12 - 0.9 + 0.779423], [R_NB - 3.3 - 0.9 + 0, BAND_Z_FRONT - 12 - 0.9 + 0.9], [R_NB - 5.3 + 0.9 + 0, BAND_Z_FRONT - 12 - 0.9 + 0.9], [R_NB - 5.3 + 0.9 + -0.45, BAND_Z_FRONT - 12 - 0.9 + 0.779423], [R_NB - 5.3 + 0.9 + -0.779423, BAND_Z_FRONT - 12 - 0.9 + 0.45], [R_NB - 5.3 + 0.9 + -0.9, BAND_Z_FRONT - 12 - 0.9 + 0], [R_NB - 5.3 + 0.9 + -0.9, BAND_Z_FRONT - 23 + 0.9 + 0], [R_NB - 5.3 + 0.9 + -0.779423, BAND_Z_FRONT - 23 + 0.9 + -0.45], [R_NB - 5.3 + 0.9 + -0.45, BAND_Z_FRONT - 23 + 0.9 + -0.779423], [R_NB - 5.3 + 0.9 + 0, BAND_Z_FRONT - 23 + 0.9 + -0.9]]);
        }
    }
    translate([X_NC + R_NB - 7, -10.5, BAND_Z_FRONT - 18.5]) {
        rotate([0, 90, 0]) {
            cylinder(h = 4, r = 1.45, center = false, $fn = 20);
        }
    }
    translate([X_NC + R_NB - 7, 10.5, BAND_Z_FRONT - 18.5]) {
        rotate([0, 90, 0]) {
            cylinder(h = 4, r = 1.45, center = false, $fn = 20);
        }
    }
}
