// H15b_cradle_jaw  (qty 2; frame: local; any)
// GENERATED by gen_halo_stl.py from halo_parts.py. Change numbers in halo_params.scad.
// Every dimension below is an expression of the names in halo_params.scad.
include <../halo_params.scad>

difference() {
    linear_extrude(height = 3, center = false) polygon([[9.5, -7], [10.074025, -6.885819], [10.56066, -6.56066], [10.885819, -6.074025], [11, -5.5], [11, 5.5], [10.885819, 6.074025], [10.56066, 6.56066], [10.074025, 6.885819], [9.5, 7], [-9.5, 7], [-10.074025, 6.885819], [-10.56066, 6.56066], [-10.885819, 6.074025], [-11, 5.5], [-11, -5.5], [-10.885819, -6.074025], [-10.56066, -6.56066], [-10.074025, -6.885819], [-9.5, -7]]);
    translate([-7, 0, -1]) {
        cylinder(h = 5, r = M3_CLEAR / 2, center = false, $fn = 20);
    }
    translate([7, 0, -1]) {
        cylinder(h = 5, r = M3_CLEAR / 2, center = false, $fn = 20);
    }
}
