// H15R_cradle_arm  (qty 1; frame: H; PETG home print preferred (fit to the bought cradle))
// GENERATED by gen_halo_stl.py from halo_parts.py. Change numbers in halo_params.scad.
// Every dimension below is an expression of the names in halo_params.scad.
include <../halo_params.scad>

rotate([90, 0, 0]) {
    difference() {
        union() {
            translate([-46, -9.5, Y_SIDE_IN - 3]) {
                cube([24, 7, Y_SIDE_IN - (Y_SIDE_IN - 3)], center = false);
            }
            translate([TRAG_X - 35 - 11, EAR_TOP_Z + 13 - 7, HBB * 0.89 + 6]) {
                cube([TRAG_X - 35 + 11 - (TRAG_X - 35 - 11), EAR_TOP_Z + 13 + 7 - (EAR_TOP_Z + 13 - 7), HBB * 0.89 + 6 + 3 - (HBB * 0.89 + 6)], center = false);
            }
            hull() {
                translate([-44, -9, Y_SIDE_IN - 3]) {
                    cube([20, 6, Y_SIDE_IN - (Y_SIDE_IN - 3)], center = false);
                }
                translate([TRAG_X - 35 - 6, EAR_TOP_Z + 13 - 6, HBB * 0.89 + 6]) {
                    cube([TRAG_X - 35 + 6 - (TRAG_X - 35 - 6), EAR_TOP_Z + 13 + 6 - (EAR_TOP_Z + 13 - 6), HBB * 0.89 + 6 + 3 - (HBB * 0.89 + 6)], center = false);
                }
            }
        }
        translate([-40, -6, Y_SIDE_IN - 4]) {
            cylinder(h = 5, r = M3_CLEAR / 2, center = false, $fn = 20);
        }
        translate([-29, -6, Y_SIDE_IN - 4]) {
            cylinder(h = 5, r = M3_CLEAR / 2, center = false, $fn = 20);
        }
        translate([TRAG_X - 35 + -7, EAR_TOP_Z + 13, HBB * 0.89 + 6 - 1]) {
            cylinder(h = 5, r = M3_CLEAR / 2, center = false, $fn = 20);
        }
        translate([TRAG_X - 35 + 7, EAR_TOP_Z + 13, HBB * 0.89 + 6 - 1]) {
            cylinder(h = 5, r = M3_CLEAR / 2, center = false, $fn = 20);
        }
    }
}
