// H16_harness_clip  (qty 6; frame: local; MJF PA12 (snap needs nylon))
// GENERATED by gen_halo_stl.py from halo_parts.py. Change numbers in halo_params.scad.
// Every dimension below is an expression of the names in halo_params.scad.
include <../halo_params.scad>

difference() {
    union() {
        rotate([0, 90, 0]) {
            difference() {
                cylinder(h = 8, r = 5.5, center = false, $fn = 40);
                translate([0, 0, -1]) {
                    cylinder(h = 10, r = 3.95, center = false, $fn = 40);
                }
            }
        }
        translate([0, -12.5, 3.5]) {
            rotate([0, 90, 0]) {
                difference() {
                    cylinder(h = 8, r = 7.3, center = false, $fn = 40);
                    translate([0, 0, -1]) {
                        cylinder(h = 10, r = 5.8, center = false, $fn = 40);
                    }
                }
            }
        }
        translate([0, -7, -1]) {
            cube([8, 2.4, 6], center = false);
        }
    }
    translate([-1, -3.1, -7]) {
        cube([10, 6.2, 3.8], center = false);
    }
    translate([-1, -24, -0.5]) {
        cube([10, 8, 8], center = false);
    }
}
