// H17_exit_clamp  (qty 1; frame: local; MJF PA12; print service OK)
// GENERATED by gen_halo_stl.py from halo_parts.py. Change numbers in halo_params.scad.
// Every dimension below is an expression of the names in halo_params.scad.
include <../halo_params.scad>

difference() {
    union() {
        cylinder(h = 12, r = SOCK_D / 2 + SOCK_WALL, center = false, $fn = 48);
        translate([0, -12.5, 0]) {
            difference() {
                cylinder(h = 12, r = 7.3, center = false, $fn = 40);
                translate([0, 0, -1]) {
                    cylinder(h = 14, r = 5.8, center = false, $fn = 40);
                }
            }
        }
        translate([-2.5, -7, 0]) {
            cube([5, 3, 12], center = false);
        }
        translate([-8, 4.5, 0]) {
            cube([16, 6.5, 12], center = false);
        }
    }
    translate([0, 0, -1]) {
        cylinder(h = 11, r = SOCK_D / 2, center = false, $fn = 48);
    }
    translate([-4, -24, -1]) {
        cube([8, 8, 14], center = false);
    }
    translate([-6.7, 5.3, 6.5]) {
        cube([13.4, 4.9, 5.6], center = false);
    }
}
