// H18a_umb_collar  (qty 1; frame: local; MJF PA12 or PETG)
// GENERATED by gen_halo_stl.py from halo_parts.py. Change numbers in halo_params.scad.
// Every dimension below is an expression of the names in halo_params.scad.
include <../halo_params.scad>

difference() {
    union() {
        cylinder(h = 14, r = 7.5, center = false, $fn = 40);
        translate([0, 6.5, 7]) {
            rotate([-90, 0, 0]) {
                cylinder(h = 5, r = 9, center = false, $fn = 48);
            }
        }
    }
    translate([0, 0, -1]) {
        cylinder(h = 16, r = 5.8, center = false, $fn = 40);
    }
    translate([-3.5, -10, -1]) {
        cube([7, 6, 16], center = false);
    }
    translate([0, 10.1, 7]) {
        rotate([-90, 0, 0]) {
            cylinder(h = 1.5, r = 7.7, center = false, $fn = 48);
        }
    }
}
