// H18b_umb_cup  (qty 1; frame: local; MJF PA12 or PETG)
// GENERATED by gen_halo_stl.py from halo_parts.py. Change numbers in halo_params.scad.
// Every dimension below is an expression of the names in halo_params.scad.
include <../halo_params.scad>

difference() {
    union() {
        cylinder(h = 6.2, r = 9, center = false, $fn = 48);
        translate([-4, -13, 0]) {
            cube([8, 5, 6.2], center = false);
        }
    }
    translate([0, 0, -0.01]) {
        cylinder(h = 3.15, r = 5.1, center = false, $fn = 40);
    }
    translate([0, 0, 4.6]) {
        cylinder(h = 2, r1 = 5, r2 = 9.5, center = false, $fn = 48);
    }
    translate([-2.5, -12.5, -1]) {
        cube([5, 3, 8], center = false);
    }
}
