// H19_zero_gauge  (qty 1; frame: local; any (tool))
// GENERATED by gen_halo_stl.py from halo_parts.py. Change numbers in halo_params.scad.
// Every dimension below is an expression of the names in halo_params.scad.
include <../halo_params.scad>

union() {
    difference() {
        difference() {
            cylinder(h = 14, r = AIR_OD / 2 + 2.2, center = false, $fn = 64);
            translate([0, 0, -1]) {
                cylinder(h = 16, r = AIR_OD / 2 + 0.15, center = false, $fn = 64);
            }
            translate([-9.6, -20, -1]) {
                cube([19.2, 16, 16], center = false);
            }
        }
        translate([-9.6, -20, -1]) {
            cube([19.2, 16, 16], center = false);
        }
    }
    difference() {
        translate([0, 0, 14]) {
            linear_extrude(height = 3, center = false) polygon([[27, -5], [28.14805, -4.771639], [29.12132, -4.12132], [29.771639, -3.14805], [30, -2], [30, 42], [29.771639, 43.14805], [29.12132, 44.12132], [28.14805, 44.771639], [27, 45], [-27, 45], [-28.14805, 44.771639], [-29.12132, 44.12132], [-29.771639, 43.14805], [-30, 42], [-30, -2], [-29.771639, -3.14805], [-29.12132, -4.12132], [-28.14805, -4.771639], [-27, -5]]);
        }
        translate([0, 0, 13]) {
            cylinder(h = 5, r = AIR_OD / 2 + 0.3, center = false, $fn = 64);
        }
        translate([-9.6, -20, 13]) {
            cube([19.2, 20, 5], center = false);
        }
    }
}
