// H20_notch_jig  (qty 1; frame: local; any (tool); PETG fine)
// GENERATED by gen_halo_stl.py from halo_parts.py. Change numbers in halo_params.scad.
// Every dimension below is an expression of the names in halo_params.scad.
include <../halo_params.scad>

difference() {
    translate([0, -9, 0]) {
        cube([70, 18, 8], center = false);
    }
    translate([-1, -(STRIP_W / 2 + 0.15), -1]) {
        cube([72, STRIP_W / 2 + 0.15 - (-(STRIP_W / 2 + 0.15)), STRIP_T + 0.2 - -1], center = false);
    }
    translate([58.5, STRIP_W / 2 - 0.5, -1]) {
        cube([3, 10 - (STRIP_W / 2 - 0.5), 10], center = false);
    }
    translate([60 - (((R_SI + STRIP_T / 2) * 10) / 57.29578), 4, 0.5]) {
        rotate([-90, 0, 0]) {
            cylinder(h = 8, r = 1.3, center = false, $fn = 20);
        }
    }
}
