#!/usr/bin/env python
"""
gen_s0_stl.py - STL generator for every printed S0 part (PROJECT SCRATCH, 14-build/S0/cad, 2026-10-02)

THE .scad FILES ARE THE SOURCE OF TRUTH for the hand-written geometry; this script rebuilds the
same solids with manifold3d (no OpenSCAD binary on the build machine) and exports STL via trimesh.
Constant names match s0_lib.scad.  Two inputs are GENERATED by dish_kinematics.py and shared by
both: pocket_mesh.json / pocket_cavity.scad (dish pocket) and dish_geometry.json /
template_paths.scad (template stylus paths).  Run dish_kinematics.py first.

Each part is modelled in its working frame (dish parts: C = ball centre at the origin, +Z up the
pad axis) and then turned into its PRINT orientation and dropped onto z = 0 before export, so every
STL opens ready to slice.  README.md gives material, layer, infill and print-service notes.

Run:   <cadenv>/bin/python gen_s0_stl.py         exit code 0 only if every STL is watertight
"""
import json, math, os, sys
import numpy as np
import trimesh
import manifold3d as m3
from manifold3d import Manifold, CrossSection

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "stl")
os.makedirs(OUT, exist_ok=True)
FN = 64

# ============================ s0_lib.scad constants ============================
# fasteners
M3_CLEAR, M3_PILOT, M3_CB_D, M3_CB_H = 3.4, 2.6, 6.2, 3.2
WOOD_SCREW = 4.5
# dish bench (C = ball centre; mm)
R_SCALP, RB, R_DC = 85.0, 3.0, 157.0
A_DOME = 26.0
DOME_ANG = (90.0, 210.0, 330.0)
NAIL_R, NAIL_ANG = 18.0, (0.0, 144.0, 216.0)
Z_DOME = math.sqrt(R_DC**2 - A_DOME**2)            # 154.83 ball centre height at home
POCKET_R = 21.0
DECK_R = 58.0
DECK_ZTOP = 175.0
LEG_R, LEG_D_TOP, LEG_D_BOT, FOOT_D = 55.0, 10.0, 7.0, 8.0
FOOT_C_R = R_SCALP + FOOT_D / 2                      # foot centres on R 89 about C
GRIP = (0.0, 45.0, 14.0, 30.0)                       # x, y, dia, height on the deck top
TPL_PIN = ((22.0, 22.0), (-22.0, -52.0))
NOSE_Z0, NOSE_Z1 = 115.5, 123.5                      # nose plate (stem guides)
BODY_Z1, TOP_Z1 = 138.0, 142.0                       # block body top / top plate top
BODY_D, TOP_D = 50.0, 62.0
BORE_D, STEM_BORE_D, STEM_D = 6.4, 4.7, 4.5
SCREW_R, SCREW_ANG = 20.0, (60.0, 180.0, 300.0)
POST_D0, POST_D1, POST_TOP = 8.0, 7.0, Z_DOME - 0.6
BALL_SOCKET_D = 6.1
WELL_D_TOP, WELL_D_BOT, WELL_Z_BOT, HOOK_Z = 24.0, 9.0, 125.5, 128.0
EAR = (-7.0, 7.0, -40.0, -24.0)                      # C-arm ear on the block (x0, x1, y0, y1), full body height
NOSE_D = 50.0
PLUNGER_D, PLUNGER_H, PLUNGER_FLOOR, CUP_D = 6.0, 7.0, 2.5, 5.3
MAG_D, MAG_H = 3.1, 2.0
SEAT_D, SEAT_H = 6.0, 1.5
NAIL_TIP_D, NAIL_TIP_R, NAIL_CONE_H = 2.0, 0.4, 1.25
PIN_HOLE_D, PIN_HOLE_DEPTH = 1.1, 5.0
def nail_len(reserve):                               # tip at max extension to the nose-plate top
    return NOSE_Z1 - (math.sqrt(R_SCALP**2 - NAIL_R**2) - reserve)
# C-arm (block frame, model coordinates)
CARM_W = 10.0
CARM_LOW_Z, CARM_LOW_H = 132.0, 6.0
CARM_RISER_Y = -88.0
CARM_TOP_Z0, CARM_TOP_H = 197.0, 8.0
STYLUS_Y = (0.0, -30.0)
DRIVE_GRIP = (14.0, 141.0, 28.0)                     # dia, z, length out from the riser (-Y): push HERE, low, near the dome plane
# templates
TPL_H, TPL_BASE, GROOVE_D, WALL_D = 19.0, 2.0, 3.4, 7.0
TPL_OUTLINE = (-26.0, 26.0, -57.0, 27.0, 6.0)
# skid ring (hand-rake mode)
SKID_Z0, SKID_T, SKID_FOOT_R = NOSE_Z0 - 3.0, 3.0, 28.0

def load_geom():
    with open(os.path.join(HERE, "pocket_mesh.json")) as f:
        pm = json.load(f)
    with open(os.path.join(HERE, "dish_geometry.json")) as f:
        dg = json.load(f)
    return pm, dg

# ============================ helpers ============================
def U(*ms):
    ms = [m for m in ms if m is not None]
    return Manifold.batch_boolean(ms, m3.OpType.Add) if len(ms) > 1 else ms[0]

def D(m, *cuts):
    cuts = [c for c in cuts if c is not None]
    if not cuts:
        return m
    return m - (Manifold.batch_boolean(cuts, m3.OpType.Add) if len(cuts) > 1 else cuts[0])

def box(x0, x1, y0, y1, z0, z1):
    return Manifold.cube([x1 - x0, y1 - y0, z1 - z0]).translate([x0, y0, z0])

def cyl(d, z0, z1, x=0.0, y=0.0, d2=None, fn=FN):
    return Manifold.cylinder(z1 - z0, d / 2, (d if d2 is None else d2) / 2, fn).translate([x, y, z0])

def sph(d, c, fn=FN):
    return Manifold.sphere(d / 2, fn).translate(list(c))

def polar(r, a_deg):
    return r * math.cos(math.radians(a_deg)), r * math.sin(math.radians(a_deg))

def revolve(pts, fn=FN):
    """pts = [(r, z)] closed profile, r >= 0, revolved about Z"""
    return Manifold.revolve(CrossSection([[list(p) for p in pts]]), fn)

def cyl_axis(d, p0, p1, fn=32):
    """cylinder of diameter d from point p0 to p1"""
    p0, p1 = np.array(p0, float), np.array(p1, float)
    v = p1 - p0
    L = float(np.linalg.norm(v))
    c = Manifold.cylinder(L, d / 2, d / 2, fn)
    z = np.array([0, 0, 1.0])
    u = v / L
    ax = np.cross(z, u)
    s = np.linalg.norm(ax)
    if s < 1e-9:
        R = np.eye(3) if u[2] > 0 else np.diag([1, -1, -1.0])
    else:
        ax /= s
        ang = math.atan2(s, float(z @ u))
        K = np.array([[0, -ax[2], ax[1]], [ax[2], 0, -ax[0]], [-ax[1], ax[0], 0]])
        R = np.eye(3) + math.sin(ang) * K + (1 - math.cos(ang)) * K @ K
    M = np.hstack([R, p0.reshape(3, 1)])
    return c.transform(M.tolist())

def to_trimesh(m):
    mm = m.to_mesh()
    return trimesh.Trimesh(vertices=np.asarray(mm.vert_properties)[:, :3], faces=np.asarray(mm.tri_verts), process=False)

def from_pts_faces(pts, faces):
    t = trimesh.Trimesh(vertices=np.asarray(pts, float), faces=np.asarray(faces, int), process=True)
    if t.volume < 0:
        t.invert()
    return Manifold(m3.Mesh(np.asarray(t.vertices, np.float32), np.asarray(t.faces, np.uint32)))

def to_bed(m, rot=None):
    """rotate (list of [rx, ry, rz] degrees applied in order) and drop onto z = 0, centred in XY"""
    if rot:
        for r in rot:
            m = m.rotate(r)
    bb = m.bounding_box()
    return m.translate([-(bb[0] + bb[3]) / 2, -(bb[1] + bb[4]) / 2, -bb[2]])

def swept(polyline, d, z0, z1, fn=24):
    """union of hulls of consecutive vertical cylinders along an XY polyline"""
    cs = [cyl(d, z0, z1, x, y, fn=fn) for x, y in polyline]
    hs = [Manifold.batch_hull([a, b]) for a, b in zip(cs[:-1], cs[1:])]
    return U(*hs)

# ============================ DISH BENCH ============================
def pocket_cavities(pm):
    cav = from_pts_faces(pm["points"], pm["faces"]).translate([0, A_DOME, 0])   # local XY -> ball home (0, 26)
    return [cav.rotate([0, 0, a - 90.0]) for a in DOME_ANG]

def leg(a):
    x, y = polar(LEG_R, a)
    zf = math.sqrt(FOOT_C_R**2 - LEG_R**2)
    shaft = cyl(LEG_D_BOT, zf, DECK_ZTOP - 3, x, y, d2=LEG_D_TOP)
    flare = cyl(LEG_D_TOP + 6, DECK_ZTOP - 10, DECK_ZTOP - 3, x, y, d2=LEG_D_TOP + 6)
    return U(shaft, flare, sph(FOOT_D, (x, y, zf)))

def deck(pm):
    z_u = pm["z_u"]
    top = cyl(2 * DECK_R, DECK_ZTOP - 3.0, DECK_ZTOP)
    shells = [cyl(2 * (POCKET_R + 2.5), z_u, DECK_ZTOP, *polar(A_DOME, a)) for a in DOME_ANG]
    island = cyl(12.0, z_u, DECK_ZTOP)
    legs = [leg(a) for a in DOME_ANG]
    gx, gy, gd, gh = GRIP
    grip = cyl(gd, DECK_ZTOP, DECK_ZTOP + gh, gx, gy, d2=gd - 2)
    body = U(top, island, grip, *shells, *legs)
    cuts = pocket_cavities(pm)
    cuts.append(cyl(3.2, z_u - 2, DECK_ZTOP + 1))                                # elastic hole
    cuts.append(box(-7.0, 7.0, -2.0, 2.0, DECK_ZTOP - 2.5, DECK_ZTOP + 1))       # toggle recess
    for x, y in TPL_PIN:
        cuts.append(cyl(M3_PILOT, DECK_ZTOP - 8, DECK_ZTOP + 1, x, y, fn=24))
    return D(body, *cuts)

def block():
    body = cyl(BODY_D, NOSE_Z1, BODY_Z1)
    top = U(cyl(TOP_D, BODY_Z1, TOP_Z1), cyl(BODY_D, BODY_Z1 - 6, BODY_Z1, d2=TOP_D))   # 45 deg chamfer under the plate rim
    ear = box(EAR[0], EAR[1], EAR[2], EAR[3], NOSE_Z1, TOP_Z1)
    posts = []
    for a in DOME_ANG:
        x, y = polar(A_DOME, a)
        posts.append(cyl(POST_D0, TOP_Z1 - 0.5, POST_TOP, x, y, d2=POST_D1))
    solid = U(body, top, ear, *posts)
    cuts = []
    for a in DOME_ANG:                                                             # ball sockets
        x, y = polar(A_DOME, a)
        cuts.append(sph(BALL_SOCKET_D, (x, y, Z_DOME), fn=48))
    for a in NAIL_ANG:
        x, y = polar(NAIL_R, a)
        cuts.append(cyl(BORE_D, NOSE_Z1 - 1, BODY_Z1, x, y, fn=40))                 # spring/plunger bore, open below
        cuts.append(cyl(M3_PILOT, BODY_Z1 - 0.5, TOP_Z1 + 1, x, y, fn=24))          # preload set-screw pilot
    for a in SCREW_ANG:
        x, y = polar(SCREW_R, a)
        cuts.append(cyl(M3_PILOT, NOSE_Z1 - 1, NOSE_Z1 + 11, x, y, fn=24))          # nose-plate screws
    slope = (WELL_D_TOP - WELL_D_BOT) / (TOP_Z1 - WELL_Z_BOT)
    cuts.append(cyl(WELL_D_BOT, WELL_Z_BOT, TOP_Z1 + 1, d2=WELL_D_TOP + slope))                     # conical elastic well
    cuts.append(cyl_axis(2.2, (-14, 0, HOOK_Z), (14, 0, HOOK_Z), fn=20))           # hook pin cross-hole
    for zz in (128.0, 135.0):                                                      # C-arm ear screws (along Y)
        cuts.append(cyl_axis(M3_PILOT, (0, EAR[2] - 1, zz), (0, EAR[2] + 12, zz), fn=20))
    return D(solid, *cuts)

def nose_plate():
    p = U(cyl(NOSE_D - 2, NOSE_Z0, NOSE_Z0 + 1, d2=NOSE_D), cyl(NOSE_D, NOSE_Z0 + 1, NOSE_Z1))   # 1 mm chamfer on the scalp side
    cuts = []
    for a in NAIL_ANG:
        x, y = polar(NAIL_R, a)
        cuts.append(cyl(STEM_BORE_D, NOSE_Z0 - 1, NOSE_Z1 + 1, x, y, fn=40))
        cuts.append(cyl(STEM_BORE_D + 1.2, NOSE_Z0 - 1, NOSE_Z0 + 0.6, x, y, d2=STEM_BORE_D, fn=40))   # lead-in chamfer
    for a in SCREW_ANG:
        x, y = polar(SCREW_R, a)
        cuts.append(cyl(M3_CLEAR, NOSE_Z0 - 1, NOSE_Z1 + 1, x, y, fn=24))
        cuts.append(cyl(M3_CB_D, NOSE_Z0 - 1, NOSE_Z0 + M3_CB_H, x, y, fn=24))
    return D(p, *cuts)

def plunger():
    p = cyl(PLUNGER_D, 0, PLUNGER_H)
    return D(p, cyl(MAG_D, -1, MAG_H, fn=32), cyl(CUP_D, PLUNGER_FLOOR, PLUNGER_H + 1, fn=40))

def seat_disc():
    return cyl(SEAT_D, 0, SEAT_H)

def nail(reserve, rings):
    """drafted nail: 90 deg tip cone from a 2.0 flat (rim R 0.4) to 4.5 at 1.25 mm, then a constant
    4.5 stem (C2 'constant stem' option) to the top; steel-pin hole in the top; ID rings."""
    L = nail_len(reserve)
    r0, r1, rf = NAIL_TIP_D / 2, STEM_D / 2, NAIL_TIP_R
    # fillet between the flat (z = 0) and the 45 deg cone: centre at (r0 - t, rf)
    t = rf * math.tan(math.radians(22.5))          # tangent length for a 135 deg corner
    cx, cz = r0 - t, rf
    prof = [(0.0, 0.0), (r0 - t, 0.0)]
    for k in range(1, 8):
        a = -math.pi / 2 + (math.pi / 4) * k / 7   # from straight down to 45 deg
        prof.append((cx + rf * math.cos(a), cz + rf * math.sin(a)))
    prof += [(r1, NAIL_CONE_H), (r1, L - 0.3), (r1 - 0.3, L), (0.0, L)]
    n = revolve(prof, 64)
    cuts = [cyl(PIN_HOLE_D, L - PIN_HOLE_DEPTH, L + 1, fn=20)]
    for k in range(rings):
        zc = L - 1.5 * (k + 1)
        cuts.append(D(cyl(STEM_D + 2, zc - 0.3, zc + 0.3), cyl(STEM_D - 0.6, zc - 0.4, zc + 0.4)))
    return D(n, *cuts)

def carm():
    lo_z0, lo_z1 = CARM_LOW_Z, CARM_LOW_Z + CARM_LOW_H
    w = CARM_W / 2
    foot = box(-w - 2, w + 2, EAR[2] - 6, EAR[2], 124.0, lo_z1)                     # bolts to the block ear
    low = box(-w, w, CARM_RISER_Y - 5, EAR[2] - 6, lo_z0, lo_z1)
    riser = box(-w, w, CARM_RISER_Y - 5, CARM_RISER_Y + 5, lo_z0, CARM_TOP_Z0 + CARM_TOP_H)
    topb = box(-w, w, CARM_RISER_Y - 5, 8.0, CARM_TOP_Z0, CARM_TOP_Z0 + CARM_TOP_H)
    g1 = Manifold.batch_hull([box(-w, w, CARM_RISER_Y + 5, CARM_RISER_Y + 6, lo_z1, lo_z1 + 14),
                              box(-w, w, CARM_RISER_Y + 5, CARM_RISER_Y + 19, lo_z1, lo_z1 + 1)])
    g2 = Manifold.batch_hull([box(-w, w, CARM_RISER_Y + 5, CARM_RISER_Y + 6, CARM_TOP_Z0 - 14, CARM_TOP_Z0),
                              box(-w, w, CARM_RISER_Y + 5, CARM_RISER_Y + 19, CARM_TOP_Z0 - 1, CARM_TOP_Z0)])
    gd, gz, gl = DRIVE_GRIP
    grip = U(cyl_axis(gd, (0, CARM_RISER_Y - 4, gz), (0, CARM_RISER_Y - 5 - gl, gz), fn=40),
             sph(gd, (0, CARM_RISER_Y - 5 - gl, gz), fn=40))
    arm = U(foot, low, riser, topb, g1, g2, grip)
    cuts = []
    for y in STYLUS_Y:
        cuts.append(cyl(M3_CLEAR, CARM_TOP_Z0 - 1, CARM_TOP_Z0 + CARM_TOP_H + 1, 0, y, fn=24))   # drop-in M3 x 25 stylus, head rests on the bar
    for zz in (128.0, 135.0):
        cuts.append(cyl_axis(M3_CLEAR, (0, EAR[2] - 7, zz), (0, EAR[2] + 1, zz), fn=24))
        cuts.append(cyl_axis(M3_CB_D, (0, EAR[2] - 7, zz), (0, EAR[2] - 6 + 2.5, zz), fn=24))
    return D(arm, *cuts)

def template(dg, name, notches):
    t = dg["templates"][name]
    x0, x1, y0, y1, rr = TPL_OUTLINE
    base = Manifold.extrude(CrossSection.square([x1 - x0 - 2 * rr, y1 - y0 - 2 * rr]).translate([x0 + rr, y0 + rr]).offset(rr, m3.JoinType.Round), TPL_BASE)
    walls, grooves = [], []
    for key in ("stylus1", "stylus2"):
        for path in t[key]:
            pts = [tuple(p) for p in path]
            walls.append(swept(pts, WALL_D, 0.0, TPL_H))
            grooves.append(swept(pts, GROOVE_D, TPL_BASE, TPL_H + 1))
    solid = U(base, *walls)
    cuts = list(grooves)
    for x, y in TPL_PIN:
        cuts.append(cyl(M3_CLEAR, -1, TPL_BASE + 1, x, y, fn=24))
    for k in range(notches):                                                       # ID notches on the +X edge
        cuts.append(box(x1 - 2.0, x1 + 1, 10.0 - 5.0 * k, 12.0 - 5.0 * k, -1, TPL_BASE + 1))
    return D(solid, *cuts)

def skid_ring():
    z0, z1 = SKID_Z0, SKID_Z0 + SKID_T
    ring = D(cyl(2 * 31, z0, z1), cyl(2 * 23.5, z0 - 1, z1 + 1))
    tabs = [cyl(10, z0, z1, *polar(SCREW_R, a)) for a in SCREW_ANG]
    webs = [Manifold.batch_hull([cyl(10, z0, z1, *polar(SCREW_R, a)), cyl(8, z0, z1, *polar(27.0, a))]) for a in SCREW_ANG]
    legs = []
    for a in SCREW_ANG:
        x, y = polar(SKID_FOOT_R, a)
        zf = math.sqrt(FOOT_C_R**2 - SKID_FOOT_R**2)
        legs.append(U(cyl(6.0, zf, z1, x, y, d2=8.0), sph(FOOT_D, (x, y, zf))))
    solid = U(ring, *tabs, *webs, *legs)
    cuts = []
    for a in SCREW_ANG:
        x, y = polar(SCREW_R, a)
        cuts.append(cyl(M3_CLEAR, z0 - 1, z1 + 1, x, y, fn=24))
        cuts.append(cyl(M3_CB_D, z0 - 1, z0 + 1.6, x, y, fn=24))
    for a in NAIL_ANG:                                                              # keep the nails clear
        cuts.append(cyl(9.0, z0 - 1, z1 + 1, *polar(NAIL_R, a)))
    return D(solid, *cuts)

def ball_cradle():
    return D(cyl(110, 0, 12), cyl(98, -1, 13), cyl(98, 7, 12.01, d2=106))

def side_mock():
    """70 x 150 side-of-head mock: torus patch, tube radius 70 (crosswise), outer radius 150
    (lengthwise), 2.4 mm shell with a perimeter skirt, top point at z = 150 before dropping to bed."""
    def torus(r_tube):
        prof = [(80.0 + r_tube * math.cos(a), r_tube * math.sin(a)) for a in np.linspace(0, 2 * math.pi, 160, endpoint=False)]
        return Manifold.revolve(CrossSection([prof]), 220).rotate([0, 90, 0])     # axis along X
    half = 62.0
    outer = torus(70.0) ^ box(-half, half, -half, half, 108.0, 160.0)
    inner = torus(67.6) ^ box(-half + 2.4, half - 2.4, -half + 2.4, half - 2.4, 100.0, 160.0)
    return outer - inner

def lift_gauge():
    parts = [box(0, 12, 0, 10, 0, 2.0)]                                           # 2.0 mm reserve tab
    for i, h in enumerate((3.0, 4.0, 5.0, 6.0, 7.0)):
        parts.append(box(12 + 12 * i, 24 + 12 * i, 0, 10, 0, h))
    g = U(*parts)
    cuts = [box(14 + 12 * i, 14.8 + 12 * i, 7.0, 10.5, h - 0.4, h + 1) for i, h in enumerate((3.0, 4.0, 5.0, 6.0, 7.0)) for _ in range(1)]
    return D(g, *cuts)

# ============================ TENDON INK RIG (S0b) ============================
DRUM_PITCH_D, DRUM_LAND_D, GROOVE_R, GROOVE_PITCH = 12.0, 12.4, 0.32, 1.0
DRUM_FL_D, HUB_D, HUB_H, FL_H = 24.0, 16.0, 8.0, 2.0
GROOVE_W, SEP_W = 5.5, 1.0
SHAFT_D, SHAFT_FLAT = 5.15, 2.1
ANCHOR_R = 9.5

def drum():
    z_f1 = HUB_H
    z_ga = z_f1 + FL_H
    z_sep = z_ga + GROOVE_W
    z_gb = z_sep + SEP_W
    z_f2 = z_gb + GROOVE_W
    z_top = z_f2 + FL_H
    solid = U(cyl(HUB_D, 0, z_f1 + 0.01), cyl(DRUM_FL_D, z_f1, z_ga), cyl(DRUM_LAND_D, z_ga - 0.01, z_f2 + 0.01),
              cyl(DRUM_FL_D, z_f2, z_top))
    cuts = []
    turns = GROOVE_W / GROOVE_PITCH
    for z0 in (z_ga, z_gb):
        cs = CrossSection.circle(GROOVE_R, 16).translate([DRUM_PITCH_D / 2, 0])
        cuts.append(Manifold.extrude(cs, GROOVE_W, int(turns * 48), -360.0 * turns).translate([0, 0, z0]))
    bore = D(cyl(SHAFT_D, -1, z_top + 1, fn=40), box(SHAFT_FLAT, 5, -5, 5, -2, z_top + 2))
    cuts.append(bore)
    cuts.append(cyl_axis(3.2, (0, 0, HUB_H / 2), (HUB_D / 2 + 1, 0, HUB_H / 2), fn=20))      # M3 grub screw onto the flat
    cuts.append(box(3.4, 6.0, -2.95, 2.95, -1.0, HUB_H / 2 + 2.95))                          # M3 nut slot, open to the motor face
    # cable anchors: groove end -> radial channel on the flange's inner face -> axial hole at
    # ANCHOR_R -> crimp sleeve pocket on the flange's outer face (outside the hub on the motor side)
    cuts.append(box(DRUM_PITCH_D / 2 - 0.4, ANCHOR_R + 0.5, -0.5, 0.5, z_ga - 1.0, z_ga + 0.01))
    cuts.append(cyl(1.0, z_f1 - 0.5, z_ga + 0.5, ANCHOR_R, 0, fn=16))
    cuts.append(box(ANCHOR_R - 1.0, DRUM_FL_D / 2 + 1, -1.1, 1.1, z_f1 - 0.01, z_f1 + 1.2))
    cuts.append(box(DRUM_PITCH_D / 2 - 0.4, ANCHOR_R + 0.5, -0.5, 0.5, z_f2 - 0.01, z_f2 + 1.0))
    cuts.append(cyl(1.0, z_f2 - 0.5, z_top + 0.5, ANCHOR_R, 0, fn=16))
    cuts.append(box(ANCHOR_R - 2.5, DRUM_FL_D / 2 + 1, -1.1, 1.1, z_top - 1.2, z_top + 1))
    cuts.append(cyl(3.1, z_top - 2.1, z_top + 1, -ANCHOR_R, 0, fn=24))                     # index magnet (Stage A)
    return D(solid, *cuts)

def motor_table():
    """one NEMA 17 hangs under the 4 mm table, shaft up; two side walls screw to the plywood."""
    w, h, t = 52.0, 30.0, 4.0
    plate = box(-w / 2, w / 2, -w / 2, w / 2, h - t, h)
    walls = [box(-w / 2, -w / 2 + 3, -w / 2, w / 2, 0, h), box(w / 2 - 3, w / 2, -w / 2, w / 2, 0, h)]
    feet = [box(-w / 2 - 12, -w / 2 + 3, -w / 2, w / 2, 0, 4), box(w / 2 - 3, w / 2 + 12, -w / 2, w / 2, 0, 4)]
    solid = U(plate, *walls, *feet)
    cuts = [cyl(23.0, h - t - 1, h + 1)]
    for sx in (-15.5, 15.5):
        for sy in (-15.5, 15.5):
            cuts.append(cyl(M3_CLEAR, h - t - 1, h + 1, sx, sy, fn=24))
    for sx in (-w / 2 - 6, w / 2 + 6):
        for sy in (-16, 16):
            cuts.append(cyl(WOOD_SCREW, -1, 5, sx, sy, fn=24))
    return D(solid, *cuts)

STOP_CABLE_Z = 30.0 + HUB_H + FL_H + GROOVE_W / 2        # groove A centre above the plywood (table top 30)

def stop_block():
    """box-end housing stop for one cable: housing ferrule seat (5.2 x 10) on +Y, 2.0 cable hole to -Y."""
    zc = STOP_CABLE_Z
    body = box(-8, 8, -7, 7, 0, zc + 8)
    flange = box(-20, 20, -7, 7, 0, 4)
    solid = U(body, flange)
    cuts = [cyl_axis(5.2, (0, 7 - 10, zc), (0, 8, zc), fn=32), cyl_axis(2.0, (0, -8, zc), (0, 0, zc), fn=20)]
    for sx in (-14, 14):
        cuts.append(cyl(WOOD_SCREW, -1, 5, sx, 0, fn=24))
    return D(solid, *cuts)

def housing_sleeve():
    return D(cyl(5.1, 0, 10), cyl(2.2, -1, 11, fn=24))

RIG_STOP_R, POST_R = 60.0, 22.0
PEN_PLATE_Z0, PEN_PLATE_Z1 = 12.0, 16.0
RIG_CABLE_Z = PEN_PLATE_Z1 + 3.0

def rig_deck():
    ring = D(cyl(2 * 76, 0, 5), cyl(2 * 66, -1, 6))
    stops = []
    cuts = []
    for a in DOME_ANG:
        blk = box(RIG_STOP_R, RIG_STOP_R + 16, -6, 6, 0, RIG_CABLE_Z + 7).rotate([0, 0, a])
        stops.append(blk)
        u = np.array(polar(1.0, a) + (0.0,))
        p_in = np.array(polar(RIG_STOP_R - 1, a) + (RIG_CABLE_Z,))
        p_out = np.array(polar(RIG_STOP_R + 17, a) + (RIG_CABLE_Z,))
        p_cb = np.array(polar(RIG_STOP_R + 6, a) + (RIG_CABLE_Z,))
        cuts.append(cyl_axis(2.0, p_in, p_out, fn=20))
        cuts.append(cyl_axis(5.2, p_cb, p_out, fn=32))
    return D(U(ring, *stops), *cuts)

def pen_plate():
    plate = cyl(60, PEN_PLATE_Z0, PEN_PLATE_Z1)
    collar = cyl(18, PEN_PLATE_Z0, PEN_PLATE_Z0 + 28, d2=16)
    cups = []
    cuts = [cyl(12.2, PEN_PLATE_Z0 - 1, PEN_PLATE_Z0 + 30, fn=48)]
    for a in (30.0, 150.0, 270.0):
        x, y = polar(20.0, a)
        cups.append(cyl(21, 8.5, PEN_PLATE_Z0 + 0.01, x, y))
        cuts.append(sph(16.4, (x, y, 8.0), fn=48))
    for a in DOME_ANG:
        x, y = polar(POST_R, a)
        cuts.append(cyl(M3_PILOT, PEN_PLATE_Z0 - 1, PEN_PLATE_Z1 + 1, x, y, fn=24))
    return D(U(plate, collar, *cups), *cuts)

# ============================ HELMET TEST (S0a) ============================
HB = (46.0, 5.0, 30.0)          # base X x Y x Z  (helmet_test.scad)
HF = (46.0, 30.0, 5.0)          # flange X x Y x Z
E6_PITCH, E6_HOLE, E6_PIN_OFF = 15.1, 5.5, 10.2

def hinge_pad():
    """L-bracket: base on the helmet side, flange out sideways; hinge pin ends up ear-to-ear."""
    zf0 = HB[2] - HF[2]
    base = box(-HB[0] / 2, HB[0] / 2, -HB[1], 0, 0, HB[2])
    flange = box(-HF[0] / 2, HF[0] / 2, -HB[1], HF[1], zf0, HB[2])
    gus = [Manifold.batch_hull([box(x, x + 3, -0.1, 0.1, 4, zf0), box(x, x + 3, -0.1, 18, zf0 - 0.1, zf0)]) for x in (12, 19)]
    cuts = []
    for y in (9.0, 9.0 + E6_PITCH):
        cuts.append(cyl(E6_HOLE, zf0 - 1, HB[2] + 1, -E6_PIN_OFF, y, fn=32))
        cuts.append(cyl(10, zf0 - 1, zf0 + 2.5, -E6_PIN_OFF, y, fn=6))
    for x in (-HB[0] / 2 + 3.5, HB[0] / 2 - 3.5):
        for z in (6.0, 17.5):
            cuts.append(box(x - 1.25, x + 1.25, -HB[1] - 1, 1, z - 2.5, z + 2.5))
    return D(U(base, flange, *gus), *cuts)

# ============================ part table ============================
def build_parts():
    pm, dg = load_geom()
    P = []
    # (file, builder, print rotation list, material, qty, note)
    P.append(("D01_dish_deck", lambda: deck(pm), [[180, 0, 0]], "PLA/PETG", 1, "upside down, top plate on bed"))
    P.append(("D02_dish_block", block, None, "PETG/PLA", 1, "upright, as modelled"))
    P.append(("D03_nose_plate", nose_plate, None, "PETG or resin", 1, "flat"))
    P.append(("D04_plunger", plunger, None, "resin or PETG", 4, "cup up"))
    P.append(("D05_seat_disc", seat_disc, None, "any", 4, "flat"))
    P.append(("D06_nail_N20_reserve2", lambda: nail(2.0, 1), [[180, 0, 0]], "resin (SLA)", 4, "tip up"))
    P.append(("D07_nail_N30_reserve3", lambda: nail(3.0, 2), [[180, 0, 0]], "resin (SLA)", 4, "tip up"))
    P.append(("D16_nail_N35_reserve3p5", lambda: nail(3.5, 3), [[180, 0, 0]], "resin (SLA)", 3, "tip up"))
    P.append(("D08_c_arm", carm, [[0, 90, 0]], "PETG/PLA", 1, "on its side"))
    P.append(("D09_template_T1_line_star", lambda: template(dg, "T1_line_star", 1), None, "PLA", 1, "base down"))
    P.append(("D10_template_T2_dpath", lambda: template(dg, "T2_dpath", 2), None, "PLA", 1, "base down"))
    P.append(("D11_template_T3_circle", lambda: template(dg, "T3_circle", 3), None, "PLA", 1, "base down"))
    P.append(("D12_skid_ring_hand_rake", skid_ring, [[180, 0, 0]], "PETG/PLA", 1, "ring on bed, legs up"))
    P.append(("D13_ball_cradle", ball_cradle, None, "PLA", 1, "flat"))
    P.append(("D14_side_mock_70x150", side_mock, [[180, 0, 0]], "PLA", 1, "dome down? no: skirt on bed (see README)"))
    P.append(("D15_lift_gauge", lift_gauge, None, "PLA", 1, "flat"))
    P.append(("H01_hinge_pad", hinge_pad, [[180, 0, 0]], "PETG/PLA", 2, "flange top on the bed"))
    P.append(("T01_drum", drum, None, "resin (SLA) or PETG", 3, "hub down"))
    P.append(("T02_motor_table", motor_table, None, "PETG/PLA", 3, "feet down"))
    P.append(("T03_stop_block", stop_block, None, "PETG/PLA", 3, "flange down"))
    P.append(("T04_housing_sleeve", housing_sleeve, None, "PETG/resin", 3, "upright"))
    P.append(("T05_rig_deck", rig_deck, None, "PLA", 1, "ring down"))
    P.append(("T06_pen_plate", pen_plate, [[180, 0, 0]], "PLA", 1, "plate top on bed"))
    return P

DENS = {"PLA": 1.24, "PETG": 1.27, "resin": 1.15}

def main(argv):
    only = None
    for a in argv:
        if a.startswith("--only="):
            only = set(a.split("=", 1)[1].split(","))
    rows, fails = [], 0
    for fname, builder, rot, mat, qty, note in build_parts():
        if only and not any(fname.startswith(o) for o in only):
            continue
        try:
            m = builder()
        except Exception as e:
            print(f"{fname}: BUILD ERROR {e!r}")
            fails += 1
            continue
        if fname == "D14_side_mock_70x150":
            m = to_bed(m)            # skirt edges on the bed, dome up (no supports)
        else:
            m = to_bed(m, rot)
        tm = to_trimesh(m)
        tm.export(os.path.join(OUT, fname + ".stl"))
        bb = m.bounding_box()
        size = [bb[i + 3] - bb[i] for i in range(3)]
        comps = [c for c in m.decompose() if c.volume() > 0]
        wt = bool(tm.is_watertight and tm.is_volume and len(comps) == 1 and m.status() == m3.Error.NoError)
        vol = m.volume() / 1000.0
        dens = DENS["resin"] if mat.startswith("resin") else DENS["PETG"] if mat.startswith("PETG") else DENS["PLA"]
        rows.append((fname, size, vol, vol * dens, wt, qty, mat, len(comps)))
        if not wt:
            fails += 1
    print(f"\n{'file':34s} {'bbox X x Y x Z (mm)':24s} {'cm3':>7s} {'g solid':>8s} {'qty':>3s} {'watertight':10s} material")
    for fname, size, vol, g, wt, qty, mat, nc in rows:
        print(f"{fname:34s} {size[0]:6.1f} x {size[1]:6.1f} x {size[2]:6.1f} {vol:7.1f} {g:8.1f} {qty:3d} {'yes' if wt else 'NO (%d parts)' % nc:10s} {mat}")
    print(f"\n{sum(1 for r in rows if r[4])}/{len(rows)} watertight")
    return 1 if fails else 0

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
